# **Week #7 - Python for ETL with Luigi I & II**

Intro to Data Engineering Course - Sekolah Engineer - Pacmann Academy

**Outline**

1. Review:
    - Python for ETL with Luigi I
    - Python for ETL with Luigi II
2. Case Study 1: Hotel Booking
3. Case Study 2: Anime & Manga Data

# <font color='blue'>Review
---

## Python for ETL with Luigi
---

### ETL Refresher
---

- Membuat ETL Pipeline adalah salah satu task utama yang dikerjakan oleh Data Engineer
- Untuk membuat ETL Pipeline yang dibuat jauh lebih maintainable dan ready for production, kita bisa menggunakan tools yang bisa melakukan itu
- Pada course ini akan menggunakan Luigi

### ETL Pipeline using Luigi
---

- Luigi bisa digunakan untuk membuat ETL Pipeline bahkan sampai level kompleks pun
- Luigi dibuat oleh Spotify untuk manage internal data processing dan workflow management
- Untuk membuat Luigi Pipeline kita harus bisa menggunakan OOP pada Python
- Karena untuk membuat Luigi Task, kita membutuhkan syntax `class`
- Method atau komponen yang umum digunakan pada Luigi adalah:
    - `requires()`
    - `run()`
    - `output()`

### Luigi Visualizer
---

- Luigi menyediakan sebuah visualizer atau UI yang bisa digunakan untuk melakukan monitoring terhadap ETL Pipeline yang dibuat
- Luigi UI hanya bisa dijalankan di **WSL** untuk OS Windows atau **UNIX** based OS
- Untuk menjalankan Luigi UI, kita masukkan command berikut di Terminal

    ```bash
    luigid --port 8082 > /dev/null 2> /dev/null &
    ```

- Setelah itu kita buka [localhost:8082](https://localhost:8082)

### Designing ETL Pipeline
---

- Seorang Data Engineer, tidak hanya membuat ETL Pipeline saja
- Tetapi, juga harus bisa melakukan Requirements Gathering yang dimana akan melakukan proses memahami problem apa yang dihadapi dan solusi yang diberikan apa
- Membuat design ETL Pipeline, merupakan salah satu solusi dari Data Engineer

### ETL Scheduling
---

- Salah satu kekurangan dari Luigi adalah tidak memiliki scheduler bawaan
- Jika ingin melakukan penjadwalan terhadap Pipeline yang dibuat di Luigi, kita bisa menggunakan Crontab
- Tahapan yang harus diperhatikan jika ingin melakukan scheduling menggunakan cron adalah:
    - Menyalakan Luigi UI Server (opsional)
    - Luigi ETL Pipeline dalam bentuk Python script
    - Bungkus menjadi Shell Script
    - Set schedule menggunakan cron untuk menjalankan Shell Script

# <font color='blue'>1. Study Case 1: Hotel Booking
---

- Data Analyst ingin melakukan analisa mengenai Transactional Data mengenai Hotel Booking
- Tetapi data tersebut masih dalam bentuk Database Docker dan terdapat di tempat lain
- Data Analyst tidak mengerti untuk
- Data Analyst meminta bantuan ke Data Engineer untuk mengekstrak data tersebut
- Akhirnya Data Engineer membuatkan ETL Pipeline untuk memudahkan proses ekstraksi data dan data akan otomatis terupdate apabila ada data terbaru
- Selain itu, nanti Data Analyst untuk melakukan analisa data cukup menggunakan data dengan format `.csv` yang hasil dari Data Pipeline yang sudah dibuat
- ETL Pipeline yang diusulkan oleh Data Engineer adalah sebagai berikut

<center>
    <img src="https://sekolahdata-assets.s3.ap-southeast-1.amazonaws.com/notebook-images/mde-intro-to-data-eng/Live-14-01_new.png" width=80%>
</center>

- Langkah - langkah yang akan kita lakukan untuk membuat ETL Pipeline adalah sebagai berikut:
    1. Explore Data untuk understanding data, tipe data, dsb
    2. Melakukan trial and error untuk metode yang ingin dipakai sebelum membuat ETL Pipeline
    3. Membuat ETL Pipeline menggunakan Luigi

**NOTE: Pada tiap tahapan proses ETL, kita akan menyimpan `.csv` file**

- Extract: `live_class_w7/data/raw/some_filename.csv`
- Transform: `live_class_w7/data/transform/some_filename.csv`
- Load: `live_class_w7/data/load/some_filename.csv`

## **1**
---

- Data yang ingin kita ekstrak didapatkan dari database yang berjalan pada Docker Container (Pull Docker Image)
- Langkah awal yang harus kita lakukan adalah download Docker Image di https://hub.docker.com/r/shandytp/hotel-booking-docker-db
- Setelah itu, kita jalankan Docker Container dan bagaimana cara menjalankannya sudah ada di dokumentasi Docker Image di atas
- Cek apakah Container sudah berjalan atau belum dengan menjalankan command `docker ps`

<center>
<img src="https://sekolahdata-assets.s3.ap-southeast-1.amazonaws.com/notebook-images/mde-intro-to-data-eng/Live-14-02.png" width=70%>
</center>

### **1a**
---

- Sebelum membuat ETL Pipeline, kita akan explore data terlebih dahulu
- Kita akan menggunakan Pandas untuk melakukan proses Extract atau fetch data di database
- Oleh karena itu, kita akan membuat koneksi terlebih dahulu

In [142]:
import pandas as pd
from sqlalchemy import create_engine

In [4]:
import pandas as pd
from sqlalchemy import create_engine

In [143]:
def postgres_engine():
    engine = create_engine("postgresql://postgres:password123@localhost:5435/etl_db")

    return engine

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
def postgres_engine():
    engine = create_engine("postgresql://postgres:password123@localhost/etl_db")

    return engine
```

</details>

---

In [144]:
engine = postgres_engine()

engine

Engine(postgresql://postgres:***@localhost:5435/etl_db)

### **1b**
---

- Setelah itu, kita akan melakukan query data yang ada di database tersebut
- Data terdapat di table `hotel_bookings`

In [147]:
query = "SELECT * FROM hotel_bookings"

hotel_data = pd.read_sql(sql = query,
                         con = engine)

hotel_data.columns

Index(['booking_id', 'hotel', 'is_canceled', 'lead_time',
       'arrival_date_week_number', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'arrival_date'],
      dtype='object')

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
query = "SELECT * FROM hotel_bookings"

hotel_data = pd.read_sql(sql = query,
                         con = engine)

hotel_data.head()
```

</details>

---

## **2**
---

- Langkah selanjutnya adalah kita akan melakukan explorasi data
- Pada tahapan ini kita akan melakukan:
    - Cek shape data
    - Cek tipe data
    - Cek missing values

### **2a**
---

Lakukan pengecekan data shape pada `hotel_data`

In [148]:
n_rows = hotel_data.shape[0]
n_cols = hotel_data.shape[1]

print(f"Hotel Booking data memiliki {n_rows} baris dan {n_cols} kolom")

Hotel Booking data memiliki 30000 baris dan 31 kolom

In [149]:
hotel_data.dtypes

booking_id                          int64
hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_week_number            int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
arrival_date                       object
dtype: object

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
n_rows = hotel_data.shape[0]
n_cols = hotel_data.shape[1]

print(f"Hotel Booking data memiliki {n_rows} baris dan {n_cols} kolom")
```

</details>

---

### **2b**
---

Lakukanlah pengecekan tipe data dari masing - masing kolom yang ada

In [13]:
for col in hotel_data.columns:

    get_data_type = hotel_data[col].dtypes

    print(f"Kolom {col} memiliki tipe data {get_data_type}")

Kolom booking_id memiliki tipe data int64
Kolom hotel memiliki tipe data object
Kolom is_canceled memiliki tipe data int64
Kolom lead_time memiliki tipe data int64
Kolom arrival_date_week_number memiliki tipe data int64
Kolom stays_in_weekend_nights memiliki tipe data int64
Kolom stays_in_week_nights memiliki tipe data int64
Kolom adults memiliki tipe data int64
Kolom children memiliki tipe data float64
Kolom babies memiliki tipe data int64
Kolom meal memiliki tipe data object
Kolom country memiliki tipe data object
Kolom market_segment memiliki tipe data object
Kolom distribution_channel memiliki tipe data object
Kolom is_repeated_guest memiliki tipe data int64
Kolom previous_cancellations memiliki tipe data int64
Kolom previous_bookings_not_canceled memiliki tipe data int64
Kolom reserved_room_type memiliki tipe data object
Kolom assigned_room_type memiliki tipe data object
Kolom booking_changes memiliki tipe data int64
Kolom deposit_type memiliki tipe data object
Kolom agent memiliki tipe data float64
Kolom company memiliki tipe data float64
Kolom days_in_waiting_list memiliki tipe data int64
Kolom customer_type memiliki tipe data object
Kolom adr memiliki tipe data float64
Kolom required_car_parking_spaces memiliki tipe data int64
Kolom total_of_special_requests memiliki tipe data int64
Kolom reservation_status memiliki tipe data object
Kolom reservation_status_date memiliki tipe data object
Kolom arrival_date memiliki tipe data object

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
for col in hotel_data.columns:

    get_data_type = hotel_data[col].dtypes

    print(f"Kolom {col} memiliki tipe data {get_data_type}")
```

</details>

---

### **2c**
---

hotel_data.dtypes

In [152]:
hotel_data.dtypes

booking_id                          int64
hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_week_number            int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
arrival_date                       object
dtype: object

In [151]:
(hotel_data.isnull().sum() * 100) / len(hotel_data)

booking_id                         0.000000
hotel                              0.000000
is_canceled                        0.000000
lead_time                          0.000000
arrival_date_week_number           0.000000
stays_in_weekend_nights            0.000000
stays_in_week_nights               0.000000
adults                             0.000000
children                           0.010000
babies                             0.000000
meal                               0.000000
country                            0.000000
market_segment                     0.000000
distribution_channel               0.000000
is_repeated_guest                  0.000000
previous_cancellations             0.000000
previous_bookings_not_canceled     0.000000
reserved_room_type                 0.000000
assigned_room_type                 0.000000
booking_changes                    0.000000
deposit_type                       0.000000
agent                             93.196667
company                           94.196667
days_in_waiting_list               0.000000
customer_type                      0.000000
adr                                0.000000
required_car_parking_spaces        0.000000
total_of_special_requests          0.000000
reservation_status                 0.000000
reservation_status_date            0.000000
arrival_date                       0.000000
dtype: float64

Sekarang, lakukanlah pengecekan missing values dari masing - masing kolom

In [14]:
for col in hotel_data.columns:
    # calculate missing values in percentage
    get_missing_values = (hotel_data[col].isnull().sum() * 100) / len(hotel_data)

    print(f"Kolom {col} memiliki missing values {get_missing_values: .2f}%")

Kolom booking_id memiliki missing values  0.00%
Kolom hotel memiliki missing values  0.00%
Kolom is_canceled memiliki missing values  0.00%
Kolom lead_time memiliki missing values  0.00%
Kolom arrival_date_week_number memiliki missing values  0.00%
Kolom stays_in_weekend_nights memiliki missing values  0.00%
Kolom stays_in_week_nights memiliki missing values  0.00%
Kolom adults memiliki missing values  0.00%
Kolom children memiliki missing values  0.01%
Kolom babies memiliki missing values  0.00%
Kolom meal memiliki missing values  0.00%
Kolom country memiliki missing values  0.00%
Kolom market_segment memiliki missing values  0.00%
Kolom distribution_channel memiliki missing values  0.00%
Kolom is_repeated_guest memiliki missing values  0.00%
Kolom previous_cancellations memiliki missing values  0.00%
Kolom previous_bookings_not_canceled memiliki missing values  0.00%
Kolom reserved_room_type memiliki missing values  0.00%
Kolom assigned_room_type memiliki missing values  0.00%
Kolom booking_changes memiliki missing values  0.00%
Kolom deposit_type memiliki missing values  0.00%
Kolom agent memiliki missing values  93.20%
Kolom company memiliki missing values  94.20%
Kolom days_in_waiting_list memiliki missing values  0.00%
Kolom customer_type memiliki missing values  0.00%
Kolom adr memiliki missing values  0.00%
Kolom required_car_parking_spaces memiliki missing values  0.00%
Kolom total_of_special_requests memiliki missing values  0.00%
Kolom reservation_status memiliki missing values  0.00%
Kolom reservation_status_date memiliki missing values  0.00%
Kolom arrival_date memiliki missing values  0.00%

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
for col in hotel_data.columns:
    # calculate missing values in percentage
    get_missing_values = (hotel_data[col].isnull().sum() * 100) / len(hotel_data)

    print(f"Kolom {col} memiliki missing values {get_missing_values: .2f}%")
```

</details>

---

## **2**
---

- Berdasarkan hasil eksplorasi tadi, kita mendapatkan beberapa temuan:
    - Terdapat missing values pada kolom `children`
    - Convert kolom `children` menjadi `int`
    - Drop kolom `agent` dan `company`
    - Convert `reservation_status_date` dan `arrival_date` menjadi datetime
    - Convert value pada kolom `is_canceled` dan `is_repeated_guest` -> True False

- Proses di atas akan kita pakai di proses Transform

### **2a**
---

- Kita tidak bisa langsung melakukan convert kolom `children` menjadi `int`
- Karena terdapat missing values pada kolom tersebut
- Oleh karena itu, kita akan impute missing values pada kolom tersebut dengan nilai `0`

In [154]:
# compare before impute
hotel_data[hotel_data["children"].isnull()]['children']

8530    NaN
9974    NaN
23110   NaN
Name: children, dtype: float64

In [155]:
hotel_data["children"] = hotel_data["children"].fillna(value = 0)

hotel_data[hotel_data["children"].isnull()]

Empty DataFrame
Columns: [booking_id, hotel, is_canceled, lead_time, arrival_date_week_number, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies, meal, country, market_segment, distribution_channel, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, reserved_room_type, assigned_room_type, booking_changes, deposit_type, agent, company, days_in_waiting_list, customer_type, adr, required_car_parking_spaces, total_of_special_requests, reservation_status, reservation_status_date, arrival_date]
Index: []

[0 rows x 31 columns]

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
hotel_data["children"] = hotel_data["children"].fillna(value = 0)

hotel_data["children"]
```

</details>

---

In [156]:
# compare after impute
hotel_data['children'].dtypes

dtype('float64')

### **2b**
---

- Setelah melakukan impute missing values, langkah selanjutnya adalah mengubah tipe data
- Kita akan ubah tipe data pada kolom `children` menjadi `int`

In [158]:
hotel_data["children"] = hotel_data["children"].astype(int)

hotel_data["children"].dtypes

dtype('int64')

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
hotel_data["children"] = hotel_data["children"].astype(int)

hotel_data["children"]
```

</details>

---

### **2c**
---

- Selanjutnya, kita akan drop kolom `agent` dan `company`
- Alasannya adalah karena kedua kolom tersebut memiliki jumlah missing values yang banyak, hampir 90%

In [163]:
# compare before drop data
hotel_data.isnull().sum()

booking_id                        0
hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_week_number          0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
arrival_date                      0
dtype: int64

In [161]:
hotel_data.drop(['agent', 'company'], axis=1, inplace=True)

In [162]:
hotel_data.shape

(30000, 29)

### **2d**
---

- Setelah itu, kita akan mengubah tipe data dari kolom `reservation_status_date` dan `arrival_date` menjadi datetime
- Karena kolom tersebut memiliki tipe data `object`
- Untuk mempermudah tim Data Analyst melakukan analisa, kita bisa convert kolom tersebut menjadi datetime

In [164]:
# compare before convert to datetime
hotel_data["reservation_status_date"].head()

0    2015-07-02
1    2016-07-13
2    2016-08-22
3    2016-09-22
4    2016-04-05
Name: reservation_status_date, dtype: object

In [168]:
[pd.to_datetime(hotel_data["reservation_status_date"]), pd.to_datetime(hotel_data["arrival_date"])]

[0       2015-07-02
 1       2016-07-13
 2       2016-08-22
 3       2016-09-22
 4       2016-04-05
            ...
 29995   2017-06-12
 29996   2016-11-11
 29997   2017-03-13
 29998   2017-02-25
 29999   2017-06-17
 Name: reservation_status_date, Length: 30000, dtype: datetime64[ns],
 0       2015-07-22
 1       2016-07-19
 2       2016-08-20
 3       2017-05-05
 4       2016-04-01
            ...
 29995   2017-06-02
 29996   2016-11-04
 29997   2017-03-10
 29998   2017-02-24
 29999   2017-06-15
 Name: arrival_date, Length: 30000, dtype: datetime64[ns]]

In [170]:
hotel_data["reservation_status_date"] = pd.to_datetime(hotel_data["reservation_status_date"])

hotel_data["reservation_status_date"]

0       2015-07-02
1       2016-07-13
2       2016-08-22
3       2016-09-22
4       2016-04-05
           ...
29995   2017-06-12
29996   2016-11-11
29997   2017-03-13
29998   2017-02-25
29999   2017-06-17
Name: reservation_status_date, Length: 30000, dtype: datetime64[ns]

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
hotel_data["reservation_status_date"] = pd.to_datetime(hotel_data["reservation_status_date"])

hotel_data["reservation_status_date"]
```

</details>

---

Jangan lupa untuk melakukan convert tipe data untuk kolom `arrival_date`

In [171]:
# compare before convert to datetime
hotel_data["arrival_date"]

0        2015-07-22
1        2016-07-19
2        2016-08-20
3        2017-05-05
4        2016-04-01
            ...
29995    2017-06-02
29996    2016-11-04
29997    2017-03-10
29998    2017-02-24
29999    2017-06-15
Name: arrival_date, Length: 30000, dtype: object

In [172]:
hotel_data["arrival_date"] = pd.to_datetime(hotel_data["arrival_date"])

hotel_data["arrival_date"]

0       2015-07-22
1       2016-07-19
2       2016-08-20
3       2017-05-05
4       2016-04-01
           ...
29995   2017-06-02
29996   2016-11-04
29997   2017-03-10
29998   2017-02-24
29999   2017-06-15
Name: arrival_date, Length: 30000, dtype: datetime64[ns]

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
hotel_data["arrival_date"] = pd.to_datetime(hotel_data["arrival_date"])

hotel_data["arrival_date"]
```

</details>

---

### **2e**
---

- Kita akan mengubah value yang ada di kolom `is_canceled` dan `is_repeated_guest`
- Value yang ingin kita ubah adalah
    - `1` ubah menjadi `True`
    - `0` ubah menjadi `False`

In [173]:
# we check the values before convert
hotel_data[["is_canceled", "is_repeated_guest"]]

       is_canceled  is_repeated_guest
0                1                  0
1                1                  0
2                0                  0
3                1                  0
4                0                  0
...            ...                ...
29995            0                  0
29996            0                  0
29997            0                  0
29998            0                  0
29999            0                  0

[30000 rows x 2 columns]

In [176]:
# initate columns and values that will be used
COLS_TO_CONVERT = ["is_canceled", "is_repeated_guest"]

CONVERT_VALUES = {
    0: False,
    1: True,
    2: "Unknown",
    "False": False,
}

for col in COLS_TO_CONVERT:
    print(f"Start converting value in column {col}")
    hotel_data[col] = hotel_data[col].replace(CONVERT_VALUES)
    print("End of process \n")

Start converting value in column is_canceled
End of process

Start converting value in column is_repeated_guest
End of process

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
# initate columns and values that will be used
COLS_TO_CONVERT = ["is_canceled", "is_repeated_guest"]

CONVERT_VALUES = {
    0: False,
    1: True
}

for col in COLS_TO_CONVERT:
    print(f"Start converting value in column {col}")
    hotel_data[col] = hotel_data[col].replace(CONVERT_VALUES)
    print("End of process \n")
```

</details>

---

In [177]:
# now we check the value
hotel_data[COLS_TO_CONVERT]

       is_canceled  is_repeated_guest
0             True              False
1             True              False
2            False              False
3             True              False
4            False              False
...            ...                ...
29995        False              False
29996        False              False
29997        False              False
29998        False              False
29999        False              False

[30000 rows x 2 columns]

## **3**
---

- Setelah kita melakukan proses trial and error, kita mencoba metode yang ingin kita pakai pada proses Transform, dsb maka langkah selanjutnya adalah membuat ETL Pipeline
- Jangan lupa, kita harus menyimpan csv files pada masing - masing tahapannya

### **3a**
---

- Pada tahapan ini, kita akan membuat Pipeline atau Task untuk Extract
- Nama task untuk melakukan Extract adalah `ExtractHotelData`
- Ketika sudah berhasil melakukan Extract, kita simpan ke dalam folder `live_class_w7/data/raw` dengan filename `extract_hotel_data.csv`

Hello

In [34]:
import luigi

In [193]:
from postgres import postgres_engine as engine_data
class ExtractHotelData(luigi.Task):

    def requires(self):
        pass

    def output(self):
        return luigi.LocalTarget("data/raw/extract_hotel_data.csv")

    def run(self):
        # initate database engine
        engine = engine_data()

        # fetch data from database
        query = "SELECT * FROM hotel_bookings"

        extract_hotel_data = pd.read_sql(sql = query,
                                         con = engine)

        extract_hotel_data.to_csv(self.output().path, index = False)

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
class ExtractHotelData(luigi.Task):

    def requires(self):
        pass

    def output(self):
        return luigi.LocalTarget("live_class_w7/data/raw/extract_hotel_data.csv")

    def run(self):
        # initate database engine
        engine = postgres_engine()

        # fetch data from database
        query = "SELECT * FROM hotel_bookings"

        extract_hotel_data = pd.read_sql(sql = query,
                                         con = engine)

        extract_hotel_data.to_csv(self.output().path, index = False)
```

</details>

---

### **3b**
---

Kita akan coba jalankan task Extract yang sudah dibuat untuk memastikan apakah bisa berjalan atau tidak

In [197]:
luigi.build([ExtractHotelData()], local_scheduler = False)

DEBUG: Checking if ExtractHotelData() is complete
INFO: Informed scheduler that task   ExtractHotelData__99914b932b   has status   DONE
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO:
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 complete ones were encountered:
    - 1 ExtractHotelData()

Did not run any tasks
This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====

True

## **4**

### **4a**
---

- Pada tahapan selanjutnya, kita akan membuat Task untuk Transform
- Nama task yang digunakan untuk melakukan proses Transform adalah `TransformHotelData`
- Proses Transform membutuhkan proses Extract sebelumnya
- Proses yang kita lakukan di Transform adalah yang sudah kita lakukan pada proses sebelumnya, yaitu:
    - Impute missing values pada kolom `children`
    - Convert kolom `children` menjadi `int`
    - Drop kolom `agent` dan `company`
    - Convert `reservation_status_date` dan `arrival_date` menjadi tipe data datetime
    - Convert value pada kolom `is_canceled` dan `is_repeated_guest`

- Ketika sudah berhasil melakukan proses Transform, kita simpan outputnya ke dalam folder `live_class_w7/data/transform` dengan filename `transform_hotel_data.csv`

In [198]:
class TransformHotelData(luigi.Task):

    def requires(self):
        return ExtractHotelData()

    def output(self):
        return luigi.LocalTarget("data/transform/transform_hotel_data.csv")

    def run(self):
        # read data from previous task
        transform_hotel_data = pd.read_csv(self.input().path)

        # impute children columns using 0 values
        transform_hotel_data["children"] = transform_hotel_data["children"].fillna(value = 0)

        # convert children columns to integer
        transform_hotel_data["children"] = transform_hotel_data["children"].astype(int)

        # drop agent and company columns
        transform_hotel_data.drop(["agent", "company"], axis = 1, inplace = True)

        # convert reservation_status_date and arrival_date columns to datetime
        transform_hotel_data["reservation_status_date"] = pd.to_datetime(transform_hotel_data["reservation_status_date"])

        transform_hotel_data["arrival_date"] = pd.to_datetime(transform_hotel_data["arrival_date"])

        # initiate values and columns to change
        CONVERT_VALUES = {
            0: False,
            1: True
        }

        COLS_TO_CONVERT = ["is_canceled", "is_repeated_guest"]

        for col in COLS_TO_CONVERT:
            print(f"Start converting value in column {col}")

            transform_hotel_data[col] = transform_hotel_data[col].replace(CONVERT_VALUES)

            print("End of process \n")

        transform_hotel_data.to_csv(self.output().path, index = False)

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
class TransformHotelData(luigi.Task):

    def requires(self):
        return ExtractHotelData()

    def output(self):
        return luigi.LocalTarget("live_class_w7/data/transform/transform_hotel_data.csv")

    def run(self):
        # read data from previous task
        transform_hotel_data = pd.read_csv(self.input().path)

        # impute children columns using 0 values
        transform_hotel_data["children"] = transform_hotel_data["children"].fillna(value = 0)

        # convert children columns to integer
        transform_hotel_data["children"] = transform_hotel_data["children"].astype(int)

        # drop agent and company columns
        transform_hotel_data.drop(["agent", "company"], axis = 1, inplace = True)

        # convert reservation_status_date and arrival_date columns to datetime
        transform_hotel_data["reservation_status_date"] = pd.to_datetime(transform_hotel_data["reservation_status_date"])

        transform_hotel_data["arrival_date"] = pd.to_datetime(transform_hotel_data["arrival_date"])

        # initiate values and columns to change
        CONVERT_VALUES = {
            0: False,
            1: True
        }

        COLS_TO_CONVERT = ["is_canceled", "is_repeated_guest"]

        for col in COLS_TO_CONVERT:
            print(f"Start converting value in column {col}")

            transform_hotel_data[col] = transform_hotel_data[col].replace(CONVERT_VALUES)

            print("End of process \n")

        transform_hotel_data.to_csv(self.output().path, index = False)
```

</details>

---

### **4b**
---

Kita akan coba jalankan task Transform yang sudah dibuat untuk memastikan apakah bisa berjalan atau tidak

In [201]:
luigi.build([ExtractHotelData(),
             TransformHotelData()], local_scheduler = True)

DEBUG: Checking if ExtractHotelData() is complete
INFO: Informed scheduler that task   ExtractHotelData__99914b932b   has status   DONE
DEBUG: Checking if TransformHotelData() is complete
INFO: Informed scheduler that task   TransformHotelData__99914b932b   has status   DONE
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO:
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 2 complete ones were encountered:
    - 1 ExtractHotelData()
    - 1 TransformHotelData()

Did not run any tasks
This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====

True

## **5**
---

- Kita sudah berhasil melakukan proses cleaning dan transformation data pada proses sebelumnya
- Maka, kita akan simpan datanya dalam bentuk `.csv` dengan filename `load_hotel_data.csv`
- Kita akan membuat task Load dengan nama `LoadHotelData`
- Bagaimana jika ada data baru pada proses Extract? Apakah kita akan menimpa file yang kita save sebelumnya?
- Untuk mengatasi hal tersebut, maka kita akan memberikan `current_timestamp` pada filename yang kita buat, sehingga menjadi `load_hotel_data_{current_timestamp}.csv`
- Sehingga, apabila ada data yang baru di data source data sebelumnya yang ada di task Load tidak tereplace
- Kita bisa menambahkan luigi parameter pada Task yang kita buat
- Untuk membuat parameternya, kita bisa menggunakan code berikut

    ```python
    current_timestamp = pd.Timestamp.now().strftime('%Y%m%d_%H%M%S')

    get_current_timestamp = luigi.Parameter(default = current_timestamp)
    ```

In [202]:
class LoadHotelData(luigi.Task):

    current_timestamp = pd.Timestamp.now().strftime('%Y%m%d_%H%M%S')

    get_current_timestamp = luigi.Parameter(default = current_timestamp)

    def requires(self):
        return TransformHotelData()

    def output(self):
        return luigi.LocalTarget(f"data/load/load_hotel_data_{self.get_current_timestamp}.csv")

    def run(self):
        load_hotel_data = pd.read_csv(self.input().path)

        load_hotel_data.to_csv(self.output().path, index = False)

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
class LoadHotelData(luigi.Task):

    current_timestamp = pd.Timestamp.now().strftime('%Y%m%d_%H%M%S')

    get_current_timestamp = luigi.Parameter(default = current_timestamp)

    def requires(self):
        return TransformHotelData()

    def output(self):
        return luigi.LocalTarget(f"live_class_w7/data/load/load_hotel_data_{self.get_current_timestamp}.csv")

    def run(self):
        load_hotel_data = pd.read_csv(self.input().path)

        load_hotel_data.to_csv(self.output().path, index = False)
```

</details>

---

In [203]:
luigi.build([LoadHotelData()], local_scheduler = True)

DEBUG: Checking if LoadHotelData(get_current_timestamp=20250106_204739) is complete
DEBUG: Checking if TransformHotelData() is complete
INFO: Informed scheduler that task   LoadHotelData_20250106_204739_73c7898d95   has status   PENDING
INFO: Informed scheduler that task   TransformHotelData__99914b932b   has status   DONE
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 14066] Worker Worker(salt=012145292, workers=1, host=DESKTOP-KIQCHDD, username=rosy, pid=14066) running   LoadHotelData(get_current_timestamp=20250106_204739)
INFO: [pid 14066] Worker Worker(salt=012145292, workers=1, host=DESKTOP-KIQCHDD, username=rosy, pid=14066) done      LoadHotelData(get_current_timestamp=20250106_204739)
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   LoadHotelData_20250106_204739_73c7898d95   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO:
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 complete ones were encountered:
    - 1 TransformHotelData()
* 1 ran successfully:
    - 1 LoadHotelData(get_current_timestamp=20250106_204739)

This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====

True

## **6**
---

- Setelah kita berhasil mencoba seluruh komponen, kita akan menjadikannya semua menjadi satu

In [60]:
class ExtractHotelData(luigi.Task):

    def requires(self):
        pass

    def output(self):
        return luigi.LocalTarget("data/raw/extract_hotel_data.csv")

    def run(self):
        # initate database engine
        engine = postgres_engine()

        # fetch data from database
        query = "SELECT * FROM hotel_bookings"

        extract_hotel_data = pd.read_sql(sql = query,
                                         con = engine)

        extract_hotel_data.to_csv(self.output().path, index = False)

class TransformHotelData(luigi.Task):

    def requires(self):
        return ExtractHotelData()

    def output(self):
        return luigi.LocalTarget("data/transform/transform_hotel_data.csv")

    def run(self):
        # read data from previous task
        transform_hotel_data = pd.read_csv(self.input().path)

        # impute children columns using 0 values
        transform_hotel_data["children"] = transform_hotel_data["children"].fillna(value = 0)

        # convert children columns to integer
        transform_hotel_data["children"] = transform_hotel_data["children"].astype(int)

        # drop agent and company columns
        transform_hotel_data.drop(["agent", "company"], axis = 1, inplace = True)

        # convert reservation_status_date and arrival_date columns to datetime
        transform_hotel_data["reservation_status_date"] = pd.to_datetime(transform_hotel_data["reservation_status_date"])

        transform_hotel_data["arrival_date"] = pd.to_datetime(transform_hotel_data["arrival_date"])

        # initiate values and columns to change
        CONVERT_VALUES = {
            0: False,
            1: True
        }

        COLS_TO_CONVERT = ["is_canceled", "is_repeated_guest"]

        for col in COLS_TO_CONVERT:
            print(f"Start converting value in column {col}")

            transform_hotel_data[col] = transform_hotel_data[col].replace(CONVERT_VALUES)

            print("End of process \n")

        transform_hotel_data.to_csv(self.output().path, index = False)

class LoadHotelData(luigi.Task):

    current_timestamp = pd.Timestamp.now().strftime('%Y%m%d_%H%M%S')

    get_current_timestamp = luigi.Parameter(default = current_timestamp)

    def requires(self):
        return TransformHotelData()

    def output(self):
        return luigi.LocalTarget(f"data/load/load_hotel_data_{self.get_current_timestamp}.csv")

    def run(self):
        load_hotel_data = pd.read_csv(self.input().path)

        load_hotel_data.to_csv(self.output().path, index = False)

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
class ExtractHotelData(luigi.Task):

    def requires(self):
        pass

    def output(self):
        return luigi.LocalTarget("live_class_w7/data/raw/extract_hotel_data.csv")

    def run(self):
        # initate database engine
        engine = postgres_engine()

        # fetch data from database
        query = "SELECT * FROM hotel_bookings"

        extract_hotel_data = pd.read_sql(sql = query,
                                         con = engine)

        extract_hotel_data.to_csv(self.output().path, index = False)

class TransformHotelData(luigi.Task):

    def requires(self):
        return ExtractHotelData()

    def output(self):
        return luigi.LocalTarget("live_class_w7/data/transform/transform_hotel_data.csv")

    def run(self):
        # read data from previous task
        transform_hotel_data = pd.read_csv(self.input().path)

        # impute children columns using 0 values
        transform_hotel_data["children"] = transform_hotel_data["children"].fillna(value = 0)

        # convert children columns to integer
        transform_hotel_data["children"] = transform_hotel_data["children"].astype(int)

        # drop agent and company columns
        transform_hotel_data.drop(["agent", "company"], axis = 1, inplace = True)

        # convert reservation_status_date and arrival_date columns to datetime
        transform_hotel_data["reservation_status_date"] = pd.to_datetime(transform_hotel_data["reservation_status_date"])

        transform_hotel_data["arrival_date"] = pd.to_datetime(transform_hotel_data["arrival_date"])

        # initiate values and columns to change
        CONVERT_VALUES = {
            0: False,
            1: True
        }

        COLS_TO_CONVERT = ["is_canceled", "is_repeated_guest"]

        for col in COLS_TO_CONVERT:
            print(f"Start converting value in column {col}")

            transform_hotel_data[col] = transform_hotel_data[col].replace(CONVERT_VALUES)

            print("End of process \n")

        transform_hotel_data.to_csv(self.output().path, index = False)

class LoadHotelData(luigi.Task):

    current_timestamp = pd.Timestamp.now().strftime('%Y%m%d_%H%M%S')

    get_current_timestamp = luigi.Parameter(default = current_timestamp)

    def requires(self):
        return TransformHotelData()

    def output(self):
        return luigi.LocalTarget(f"live_class_w7/data/load/load_hotel_data_{self.get_current_timestamp}.csv")

    def run(self):
        load_hotel_data = pd.read_csv(self.input().path)

        load_hotel_data.to_csv(self.output().path, index = False)
```

</details>

---

Jalankan ETL Pipeline yang sudah digabungkan

In [204]:
luigi.build([
    ExtractHotelData(),
    TransformHotelData(),
    LoadHotelData()])

DEBUG: Checking if ExtractHotelData() is complete
INFO: Informed scheduler that task   ExtractHotelData__99914b932b   has status   DONE
DEBUG: Checking if TransformHotelData() is complete
INFO: Informed scheduler that task   TransformHotelData__99914b932b   has status   DONE
DEBUG: Checking if LoadHotelData(get_current_timestamp=20250106_204739) is complete
INFO: Informed scheduler that task   LoadHotelData_20250106_204739_73c7898d95   has status   DONE
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO:
===== Luigi Execution Summary =====

Scheduled 3 tasks of which:
* 3 complete ones were encountered:
    - 1 ExtractHotelData()
    - 1 LoadHotelData(get_current_timestamp=20250106_204739)
    - 1 TransformHotelData()

Did not run any tasks
This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====

INFO: Worker Worker(salt=1026473195, workers=1, host=DESKTOP-KIQCHDD, username=rosy, pid=14066) was stopped. Shutting down Keep-Alive thread

True

# <font color='blue'>2. Study Case 2: Anime & Manga Data
---

**[DISCLAIMER]: For learning purposes only!**

- Samsudin adalah Data Scientist yang ingin membuat Recommender System tentang entertainment system terutama tentang Anime dan Manga
- Tetapi, untuk membuat Recommender System tersebut Samsudin membutuhkan data informasi tentang Anime dan Manga, seperti judul, genre, nama studio, dll
- Akhirnya, Samsudin meminta tolong ke Cahya Data Engineer untuk generate data mengenai informasi Anime dan Manga
- Cahya memberikan solusi sebagai berikut:
    - Untuk Anime data akan melakukan Web Scraping di [MyAnimeList](https://myanimelist.net/)
    - Untuk Manga data akan menggunakan API dari [Jikan API](https://jikan.moe/)
- Setelah itu, seluruh data yang sudah di proses dari Anime dan Manga Data akan dimasukkan ke dalam satu database yang sama yaitu `recommender_system_db`

- Untuk arsitektur ETL Pipeline yang dibuat oleh Cahya adalah sebagai berikut

<center>
<img src="https://sekolahdata-assets.s3.ap-southeast-1.amazonaws.com/notebook-images/mde-intro-to-data-eng/Live-14-03.png" width=60%>
</center>

- Untuk schema database Load adalah sebagai berikut

<center>
<img src="https://sekolahdata-assets.s3.ap-southeast-1.amazonaws.com/notebook-images/mde-intro-to-data-eng/Live-14-09.png" width=60%>
</center>

### **Breakdown Problem**
---

#### **Anime Data**
---

<center>
<img src="https://sekolahdata-assets.s3.ap-southeast-1.amazonaws.com/notebook-images/mde-intro-to-data-eng/Live-14-04.png" width=60%>
</center>

- Data yang ingin kita scrapping adalah sebuah website MyAnimeList
- Pada website tersebut terdapat informasi seperti judul, tanggal tayang, jumlah episode, dsb
- Informasi yang ingin kita extract adalah Seasonal Anime
- Untuk struktur URL yang ingin kita scrapping adalah https://myanimelist.net/anime/season/{year}/{season}
- Untuk `year` kita akan gunakan `2024` dan season kita akan gunakan `summer`, `winter`, dan `spring`

<center>
<img src="https://sekolahdata-assets.s3.ap-southeast-1.amazonaws.com/notebook-images/mde-intro-to-data-eng/Live-14-06.png" width=60%>
</center>

- Dapat dilihat, kalau ada beberapa jenis tayangan seperti `TV`, `ONA`, `OVA`, dan `Movie`

#### **Manga Data**
---

<center>
<img src="https://sekolahdata-assets.s3.ap-southeast-1.amazonaws.com/notebook-images/mde-intro-to-data-eng/Live-14-05.png" width=60%>
</center>

- Untuk mengambil data Manga, kita akan menggunakan Jikan API
- Kita bisa merujuk ke dokumentasi yang ada di https://docs.api.jikan.moe/
- Ada beberapa informasi yang harus diperhatikan, seperti ada Rate Limiting ketika akses API
- Sehingga, kita harus memberikan jeda ketika menggunakan API

<center>
<img src="https://sekolahdata-assets.s3.ap-southeast-1.amazonaws.com/notebook-images/mde-intro-to-data-eng/Live-14-07.png" width=20%>
</center>

- API yang digunakan untuk mengambil informasi mengenai Manga data adalah https://api.jikan.moe/v4/manga/{id}/full

In [64]:
import pandas as pd
import luigi
import requests
from bs4 import BeautifulSoup
from tqdm import tqdm
import time

## **1**
---

Workflow yang kita gunakan untuk task Anime data ini adalah
1. Scrape Website Anime Data
2. Trial and Error terhadap method yang ingin dipakai saat proses Transform sebelum membuat ETL Pipeline
3. Membuat ETL Pipeline

### **1a**
---

- Diberikan URL https://myanimelist.net/anime/season/{year}/{season}
- Pada case ini kita akan mengambil data dengan parameter berikut:
    - `year`: `2024`
    - `season`: `winter`
- Buat koneksi dan cek status code nya

In [205]:
resp = requests.get("https://myanimelist.net/anime/season/2024/winter")

resp.status_code

200

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
resp = requests.get("https://myanimelist.net/anime/season/2024/winter")

resp.status_code
```

</details>

---

### **1b**
---

Buatlah objek untuk menyimpan BeautifulSoup agar bisa melakukan proses scraping data

In [206]:
soup = BeautifulSoup(resp.text, "html.parser")

soup

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html class="appearance-none" lang="en"><head>
<link crossorigin="anonymous" href="//www.googletagmanager.com/" rel="preconnect"/>
<link crossorigin="anonymous" href="https://cdn.myanimelist.net" rel="preconnect"/>
<title>
Winter 2024 - Anime - MyAnimeList.net
</title>
<meta content="Looking for information on the winter season, 2024? MyAnimeList has got you covered! Join the online community, create your anime and manga list, read reviews, explore the forums, follow news, and so much more!" name="description"/>
<meta content="anime, myanimelist, anime news, manga" name="keywords"/>
<meta content="en_US" property="og:locale"/><meta content="360769957454434" property="fb:app_id"/><meta content="MyAnimeList.net" property="og:site_name"/><meta content="summary" name="twitter:card"/><meta content="@myanimelist" name="twitter:site"/><meta content=" Winter 2024 - Anime - MyAnimeList.net " property="og:title"/><meta content="https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png" property="og:image"/><meta content="https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png" name="twitter:image:src"/><meta content="https://myanimelist.net/anime/season/2024/winter" property="og:url"/><meta content="Looking for information on the winter season, 2024? MyAnimeList has got you covered! Join the online community, create your anime and manga list, read reviews, explore the forums, follow news, and so much more!" property="og:description"/>
<meta content="default" name="referrer"/><link href="/manifest.json" rel="manifest"/>
<meta content="18c111ebf7afb4f85c7a353d3032a398d8b3cdde" name="csrf_token"/>
<meta content="1e927243-8e02-48e3-b098-a7b78c5b4e36" name="fo-verify"/><meta content="initial-scale=1" name="viewport"><link as="style" href="https://cdn.myanimelist.net/static/assets/css/pc/style-2646526df2.css" rel="preload">
<link as="style" href="https://cdn.myanimelist.net/static/assets/css/pc/dark-6b32e9457a.css" rel="preload"/>
<link as="script" href="https://cdn.myanimelist.net/static/assets/js/pc/header-e0eab69c04.js" rel="preload"/>
<link as="script" href="https://cdn.myanimelist.net/static/assets/js/pc/all-bb006ddc14.js" rel="preload"/>
<link href="https://cdn.myanimelist.net/static/assets/css/pc/style-2646526df2.css" rel="stylesheet" type="text/css"/>
<link href="https://cdn.myanimelist.net/static/assets/css/pc/dark-6b32e9457a.css" rel="stylesheet" type="text/css"/>
<script src="https://cdn.myanimelist.net/static/assets/js/pc/header-e0eab69c04.js" type="text/javascript"></script>
<script async="async" data-params='{"origin_url":"https:\/\/myanimelist.net"}' id="alljs" src="https://cdn.myanimelist.net/static/assets/js/pc/all-bb006ddc14.js" type="text/javascript"></script>
<link href="https://myanimelist.net/plugins/myanimelist.xml" rel="search" title="MyAnimeList" type="application/opensearchdescription+xml"/>
<link href="https://cdn.myanimelist.net/images/favicon.ico" rel="shortcut icon"/>
<meta content="6Ld_1aIZAAAAAF6bNdR67ICKIaeXLKlbhE7t2Qz4" name="recaptcha_site_key"/>
<script>
window.GRECAPTCHA_SITE_KEY = '6Ld_1aIZAAAAAF6bNdR67ICKIaeXLKlbhE7t2Qz4';
</script>
<script async="" defer="" src="https://www.google.com/recaptcha/api.js?render=6Ld_1aIZAAAAAF6bNdR67ICKIaeXLKlbhE7t2Qz4"></script>
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700&amp;display=swap" rel="stylesheet"/>
<script async="" crossorigin="anonymous" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1473193330168238"></script>
<script src="https://cdn.myanimelist.net/js/quantcast_choice.js?v=1736172714" type="text/javascript"></script>
<script src="https://cdn.myanimelist.net/js/cmp.js?v=1736172714" type="text/javascript"></script>
<script async="" src="https://btloader.com/tag?o=5110059113906176&amp;upapi=true"></script> <script async="" data-mode="scan" data-site-id="65a1835ac178db4aeb9540ce" src="https://hb.vntsm.com/v3/live/ad-manager.min.js" type="text/javascript"></script>
<script>
  var clientDarkMode = window.matchMedia("(prefers-color-scheme:dark)").matches;
  let darkMode = false

  if (clientDarkMode) {
    if (!$('html').hasClass("appearance-light")) { // SystemSetting = Dark && MAL UserSettings != Light
      darkMode = true
    }
  } else if ($('html').hasClass("appearance-dark")) { // MAL UserSettings = Dark
    darkMode = true
  }

    if (darkMode) {
    $('html').addClass("dark-mode");
  }
    $(document).ready(function() {
    if (darkMode) {
      if($('.js-color-pc-constant').length){$('.js-color-pc-constant').addClass("color-pc-constant");}
    }
  });
</script>
</link></meta></head>
<body class="page-common season" data-country-code="ID" data-ms="false" data-time="1736172714">
<div id="myanimelist">
<script type="text/javascript">
    window.MAL.SkinAd.prepareForSkin('');
  </script>
<div class="ad-skin-side-outer ad-skin-side-bg bg-left" id="ad-skin-bg-left">
<div class="ad-skin-side left" id="ad-skin-left" style="display: none;">
<div id="ad-skin-left-absolute-block">
<div id="ad-skin-left-fixed-block"></div>
</div>
</div>
</div><div class="wrapper">
<div class="" id="headerSmall"> <script>(deployads = window.deployads || []).disablePageSegmentSessionTracking = true; </script>
<script>(deployads = window.deployads || []).pageSegment = 'anime_season';</script>
<script>
    var trackOutboundLink = function(url) {
        ga('send', 'event', 'outbound', 'click', url, {
            'transport': 'beacon',
            'hitCallback': function(){return true;}
        });
    }
</script><div class="banner-header-anime-straming header-mini-banner" style="right:480px;">
<a href="https://mxj.myanimelist.net/" onclick="trackOutboundLink('https://mxj.myanimelist.net/')">
<img alt="MAL x JAPAN" height="36" src="/c/img/images/event/20210527_MALxJAPAN_MiniBanner/500x72_miniBanner_B.png" title="MAL x JAPAN" width="250"/>
</a>
</div>
<div id="header-menu"><div class="header-menu-login"><a class="btn-mal-service ga-click ga-impression" data-ga-click-type="hide-ads" data-ga-impression-type="hide-ads" href="https://myanimelist.net/membership?_location=mal_h_u" onclick="ga_mal_banner()">Hide Ads</a><a class="btn-login" href="https://myanimelist.net/login.php?from=%2Fanime%2Fseason%2F2024%2Fwinter" id="malLogin" onclick="ga_notlogin()">Login</a><a class="btn-signup" href="https://myanimelist.net/register.php?from=%2Fanime%2Fseason%2F2024%2Fwinter" onclick="ga_registration()">Sign Up</a></div></div><a class="link-mal-logo" href="/">MyAnimeList.net</a></div>
<div class="" id="menu">
<div id="menu_right"><script id="incremental-result-item-anime" type="text/x-template"><div class="list anime" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info anime"><div class="name">${ item.name } <span class="media-type">(${ item.payload.media_type })</span></div><div class="extra-info">Aired: ${ item.payload.aired }<br>Score: ${ item.payload.score }<br>Status: ${ item.payload.status }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info anime"><div class="name">${ item.name }</div><div class="media-type">(${ mediaTypeWithStartYear })</div></div></div></a></div></script><script id="incremental-result-item-manga" type="text/x-template"><div class="list manga" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info manga"><div class="name">${ item.name } <span class="media-type">(${ item.payload.media_type })</span></div><div class="extra-info">Published: ${ item.payload.published }<br>Score: ${ item.payload.score }<br>Status: ${ item.payload.status }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info manga"><div class="name">${ item.name }</div><div class="media-type">(${ mediaTypeWithStartYear })</div></div></div></a></div></script><script id="incremental-result-item-character" type="text/x-template"><div class="list character" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info character"><div class="name"  v-html="item.name"></div><div class="extra-info"><ul class="related-works"><li v-for="work in item.payload.related_works" class="fs-i">- ${ work }</li></ul>Favorites: ${ item.payload.favorites }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info character"><div class="name"  v-html="item.name"></div></div></div></a></div></script><script id="incremental-result-item-person" type="text/x-template"><div class="list person" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info person"><div class="name">${ item.name }</div><div class="extra-info"><span v-if="item.payload.alternative_name">${ item.payload.alternative_name }<br></span>Birthday: ${ item.payload.birthday }<br>Favorites: ${ item.payload.favorites }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info person"><div class="name">${ item.name }</div></div></div></a></div></script><script id="incremental-result-item-company" type="text/x-template"><div class="list company" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info company"><div class="name">${ item.name }</div><div class="extra-info"><span v-if="item.payload.japanese">(${ item.payload.japanese })<br></span>
                        Anime titles: ${ item.payload.num_animes.toLocaleString() }<br>
                        Favorites: ${item.payload.favorites.toLocaleString()}
                    </div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info company"><div class="name">${ item.name }</div></div></div></a></div></script><script id="incremental-result-item-store" type="text/x-template"><div class="list store" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info store"></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info store"></div></div></a></div></script><script id="incremental-result-item-club" type="text/x-template"><div class="list club" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info club"><div class="name">${ item.name }</div><div class="extra-info">Members: ${ item.payload.members }<br>Category: ${ item.payload.category }<br>Created by: ${ item.payload.created_by }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info club"><div class="name">${ item.name }</div></div></div></a></div></script><script id="incremental-result-item-user" type="text/x-template"><div class="list user" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info user"><div class="name">${ item.name }</div><div class="extra-info"><span v-if="item.payload.authority">${ item.payload.authority }<br></span>Joined: ${ item.payload.joined }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info user"><div class="name">${ item.name }</div></div></div></a></div></script><script id="incremental-result-item-news" type="text/x-template"><div class="list news" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info news"><div class="name">${ item.name }</div><div class="extra-info">${ item.payload.date }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info news"><div class="name">${ item.name }</div><div class="media-type">${ item.payload.date }</div></div></div></a></div></script><script id="incremental-result-item-featured" type="text/x-template"><div class="list featured" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info featured"><div class="name">${ item.name }</div><div class="extra-info">${ item.payload.date }</div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info featured"><div class="name">${ item.name }</div><div class="media-type">${ item.payload.date }</div></div></div></a></div></script><script id="incremental-result-item-forum" type="text/x-template"><div class="list forum" :class="{'focus': focus}"><a :href="url" class="clearfix"><div class="on" v-if="focus"><span class="image" :style="{'background-image': 'url(' + item.image_url + ')'}"></span><div class="info forum"><div class="name"><span v-show="item.payload.work_title">${ item.payload.work_title}
                      <i class="fa-solid fa-caret-right"></i></span> ${ item.name }</div><div class="extra-info">${ item.payload.date }<br><span>in ${ item.payload.category }</span></div></div></div><div class="off" v-if="!focus"><span class="image" :style="{'background-image': 'url(' + item.thumbnail_url + ')'}"></span><div class="info forum"><div class="name"><span v-show="item.payload.work_title">${ item.payload.work_title}
                      <i class="fa-solid fa-caret-right"></i></span> ${ item.name }</div><div class="media-type">${ item.payload.date }</div></div></div></a></div></script><script id="incremental-result-item-separator" type="text/x-template"><div class="list separator"><div class="separator"><span v-show="item.name == 'anime'">Anime</span><span v-show="item.name == 'manga'">Manga</span><span v-show="item.name == 'character'">Characters</span><span v-show="item.name == 'person'">People</span><span v-show="item.name == 'company'">Companies</span></div></div></script><div class="js-color-pc-constant" id="top-search-bar"><form @submit.prevent="jump()" class="searchBar" id="searchBar" method="get"><div class="form-select-outer fl-l"><select class="inputtext" id="topSearchValue" name="type" v-model="type"><option value="all">All</option><option value="anime">Anime</option><option value="manga">Manga</option><option value="character">Characters</option><option value="person">People</option><option value="company">Companies</option><option value="store">Manga Store</option><option value="news">News</option><option value="featured">Featured Articles</option><option value="forum">Forum</option><option value="club">Clubs</option><option value="user">Users</option></select></div><input @blur="isFocused = false" @focus="isFocused = true" @keydown.down.prevent="moveSelection(1)" @keydown.up.prevent="moveSelection(-1)" autocomplete="off" class="inputtext fl-l" id="topSearchText" name="topkeyword" placeholder="Search Anime, Manga, and more..." size="30" type="search" v-model="keyword"/><button :class="{'notActive': (keyword.length &lt; 3)}" class="fl-l" id="topSearchButon" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button></form><div :style="{display: (showResult ? 'block' : 'none')}" @mousedown.prevent="" class="incrementalSearchResultList" id="topSearchResultList"><div @mouseover="selection=i" v-for="(item, i) in items"><component :focus="selection == i" :is="resolveComponent(item)" :item="item" :url="generateItemPageUrl(item)"></component></div><div :class="{'focus': selection == -1}" :style="{display: (showViewAllLink ? 'block' : 'none')}" @mouseover="selection = -1" class="list list-bottom"><a :href="resultPageUrl">
              View all results for <span class="fw-b">${ keyword }</span><i class="fa-solid fa-spinner fa-spin ml4" v-show="isRequesting"></i></a></div></div></div></div><div id="menu_left">
<ul class="js-color-pc-constant" id="nav">
<li class="small"><a class="non-link" href="#">Anime</a>
<ul class="x-wider">
<li><a href="https://myanimelist.net/anime.php?_location=mal_h_m">Anime Search</a></li>
<li><a href="https://myanimelist.net/topanime.php?_location=mal_h_m">Top Anime</a></li>
<li><a href="https://myanimelist.net/anime/season?_location=mal_h_m">Seasonal Anime</a></li>
<li><a href="https://myanimelist.net/watch/episode?_location=mal_h_m_a">Videos</a></li>
<li><a href="https://myanimelist.net/reviews.php?t=anime&amp;_location=mal_h_m">Reviews</a></li>
<li><a href="https://myanimelist.net/recommendations.php?s=recentrecs&amp;t=anime&amp;_location=mal_h_m">Recommendations</a></li>
<li><a href="https://myanimelist.net/forum?topicid=2138549&amp;_location=mal_h_m">2024 Challenge</a></li><li><a href="https://fal.myanimelist.net/?utm_source=MAL&amp;utm_medium=headermenu&amp;utm_campaign=fal&amp;utm_content=falhome&amp;_location=mal_h_m">Fantasy Anime League</a></li></ul>
</li>
<li class="small"><a class="non-link" href="#">Manga</a>
<ul class="x-wider">
<li><a href="https://myanimelist.net/manga.php?_location=mal_h_m">Manga Search</a></li>
<li><a href="https://myanimelist.net/topmanga.php?_location=mal_h_m">Top Manga</a></li>
<li><a class="menu-new" href="https://myanimelist.net/manga/adapted?_location=mal_h_m">Adapted to Anime</a></li>
<li><a href="https://myanimelist.net/store?_location=mal_h_m">Manga Store</a></li>
<li><a href="https://myanimelist.net/reviews.php?t=manga&amp;_location=mal_h_m">Reviews</a></li>
<li><a href="https://myanimelist.net/recommendations.php?s=recentrecs&amp;t=manga&amp;_location=mal_h_m">Recommendations</a></li>
<li><a href="https://myanimelist.net/forum?topicid=2141704&amp;_location=mal_h_m">2024 Challenge</a></li>
</ul>
</li>
<li><a class="non-link" href="#">Community</a>
<ul>
<li><a href="https://myanimelist.net/stacks?_location=mal_h_m">Interest Stacks</a></li>
<li><a href="https://myanimelist.net/forum/?_location=mal_h_m">Forums</a></li>
<li><a href="https://myanimelist.net/clubs.php?_location=mal_h_m">Clubs</a></li>
<li><a href="https://myanimelist.net/blog.php?_location=mal_h_m">Blogs</a></li>
<li><a href="https://myanimelist.net/users.php?_location=mal_h_m">Users</a></li>
</ul>
</li>
<li class="small2"><a class="non-link" href="#">Industry</a>
<ul class="wider">
<li><a href="https://myanimelist.net/news?_location=mal_h_m">News</a></li>
<li><a href="https://myanimelist.net/featured?_location=mal_h_m">Featured Articles</a></li>
<li><a href="https://myanimelist.net/people.php?_location=mal_h_m">People</a></li>
<li><a href="https://myanimelist.net/character.php?_location=mal_h_m">Characters</a></li>
<li><a href="https://myanimelist.net/company?_location=mal_h_m">Companies</a></li>
<li><a href="https://mxj.myanimelist.net/?_location=mal_h_m">MAL×Japan</a></li>
</ul>
</li>

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
soup = BeautifulSoup(resp.text, "html.parser")

soup
```

</details>

---

## **2**
---

- Setelah dilihat, ternyata struktur website untuk show type `TV`, `OVA`, `ONA`, dan `Movie` berbeda
- Oleh karena itu, kita perlu scraping satu - persatu dan setelah itu nanti datanya kita merge menjadi satu
- Komponen yang ingin kita scrape, terdapat di satu card ini yang dimana memuat beberapa informasi

<center>
<img src="https://sekolahdata-assets.s3.ap-southeast-1.amazonaws.com/notebook-images/mde-intro-to-data-eng/Live-14-08.png" width=30%>
</center>

- Informasi yang ingin kita scrape:
    - `Title`
    - `Link MAL`
    - `Release Date`
    - `Anime Episode`
    - `Anime Duration`
    - `Anime Genre`
    - `Link Image`
    - `Description`
    - `Studio`
    - `Source`
    - `Show Type`

- Untuk `Show Type` akan kita isi secara manual, tergantung dari kita melakukan scrape show type apa
- Setelah di cek, html tag `<div>` dari masing - masing show type memiliki `class` sebagai berikut
    - `TV`: `js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-1`
    - `ONA`: `js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-5`
    - `OVA`: `js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-2`
    - `Movie`: `js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-3`

### **2a**
---

- Kita akan scrape website yang memiliki show type `TV`
- Pertama kita akan mengambil data html dari `class` dari show type `TV`

In [ ]:
anime_raw_data = soup.find_all("div", class_ = "js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-1")

anime_raw_data

[<div class="js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-1" data-broadcast-available="1" data-genre="1,2,10,50,82">
 <div>
 <div class="title"><div class="title-text">
 <h2 class="h2_anime_title"><a class="link-title" href="https://myanimelist.net/anime/52299/Ore_dake_Level_Up_na_Ken">Ore dake Level Up na Ken</a></h2></div>
 <span class="js-members" style="display: none;">818817</span>
 <span class="js-score" style="display: none;">8.27</span>
 <span class="js-start_date" style="display: none;">20240107</span>
 <span class="js-title" style="display: none;">Ore dake Level Up na Ken</span>
 </div>
 <div class="prodsrc">
 <div class="video"><a class="ga-click" href="https://myanimelist.net/anime/52299/Ore_dake_Level_Up_na_Ken/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a> </div>
 <div class="info"><span class="item">Jan 7, 2024</span><span class="item">
 <span>12 eps</span>,
           <span>23 min </span>
 </span>
 </div>
 <div class="broadcast"><a class="js-broadcast-button ga-click" data-ga-click-param="aid:52299" data-ga-click-type="broadcast-tile-streaming-icon" data-raw='{"data":[{"platform":{"id":1,"name":"Crunchyroll","icon":"crunchyroll","type":1},"available":true,"url":"http:\/\/www.crunchyroll.com\/series-283771"},{"platform":{"id":2,"name":"Netflix","icon":"netflix","type":1},"available":false,"url":"https:\/\/www.netflix.com\/"},{"platform":{"id":11,"name":"Ani-One Asia","icon":"ani-oneasia","type":2},"available":true,"url":"https:\/\/www.youtube.com\/channel\/UC0wNSTMWIL3qaorLx0jie6A"},{"platform":{"id":13,"name":"Aniplus TV","icon":"aniplustv","type":2},"available":false,"url":"http:\/\/www.aniplustv.com\/"},{"platform":{"id":16,"name":"Bahamut Anime Crazy","icon":"bahamutanimecrazy","type":2},"available":false,"url":"https:\/\/ani.gamer.com.tw\/"},{"platform":{"id":18,"name":"Bilibili Global","icon":"bilibiliintl","type":2},"available":true,"url":"https:\/\/www.bilibili.tv\/en\/index"},{"platform":{"id":19,"name":"CatchPlay","icon":"catchplay","type":2},"available":true,"url":"https:\/\/www.catchplay.com\/"},{"platform":{"id":23,"name":"iQIYI","icon":"iqiyi","type":2},"available":true,"url":"https:\/\/www.iq.com\/"}],"count":{"available":5,"typicals":2,"others":6,"total":8}}' data-subtitle="" data-title="Ore dake Level Up na Ken" href="javascript:void(0)" onclick="return false;"><i class="malicon malicon-streaming"></i></a> <a class="broadcast-item ga-click" data-available="1" data-ga-click-param="aid:52299" data-ga-click-type="broadcast-tile-streaming-platforms" href="http://www.crunchyroll.com/series-283771" title="Crunchyroll"><i class="spicon spicon-crunchyroll"></i></a></div>
 </div>
 <div class="genres js-genre" id="52299">
 <div class="genres-inner js-genre-inner"><span class="genre">
 <a href="/anime/genre/1/Action" title="Action">Action</a>
 </span><span class="genre">
 <a href="/anime/genre/2/Adventure" title="Adventure">Adventure</a>
 </span><span class="genre">
 <a href="/anime/genre/10/Fantasy" title="Fantasy">Fantasy</a>
 </span></div>
 </div>
 </div>
 <div class="image"><a href="https://myanimelist.net/anime/52299/Ore_dake_Level_Up_na_Ken"><img alt="Ore dake Level Up na Ken" src="https://cdn.myanimelist.net/images/anime/1801/142390.jpg" srcset="https://cdn.myanimelist.net/images/anime/1801/142390.jpg 1x, https://cdn.myanimelist.net/images/anime/1801/142390.jpg 2x" width="167"/></a> <a class="link-image" href="https://myanimelist.net/anime/52299/Ore_dake_Level_Up_na_Ken">Ore dake Level Up na Ken</a>
 </div>
 <div class="synopsis js-synopsis">
 <p class="preline">Humanity was caught at a precipice a decade ago when the first gates—portals linked with other dimensions that harbor monsters immune to conventional weaponry—emerged around the world. Alongside the appearance of the gates, various humans were transformed into hunters and bestowed superhuman abilities. Responsible for entering the gates and clearing the dungeons within, many hunters chose to form guilds to secure their livelihoods.

 Sung Jin-Woo is an E-rank hunter dubbed as the weakest hunter of all mankind. While exploring a supposedly safe dungeon, he and his party encounter an unusual tunnel leading to a deeper area. Enticed by the prospect of treasure, the group presses forward, only to be confronted with horrors beyond their imagination. Miraculously, Jin-Woo survives the incident and soon finds that he now has access to an interface visible only to him. This mysterious system promises him the power he has long dreamed of—but everything comes at a price.

 [Written by MAL Rewrite]</p>
 <button class="js-toggle-text toggle-text" style="display: block; margin: 0 auto; background: none; border: none;">
 <i class="fa-solid fa-angle-down" style="pointer-events: none;"></i>
 </button>
 <div class="properties">
 <div class="property">
 <span class="caption">Studio</span><span class="item"><a href="/anime/producer/56/A-1_Pictures" title="A-1 Pictures">A-1 Pictures</a></span></div>
 <div class="property">
 <span class="caption">Source</span><span class="item">Web manga</span>
 </div><div class="property">
 <span class="caption">Themes</span><span class="item"><a href="/anime/genre/50/Adult_Cast" title="Adult Cast">Adult Cast</a></span><span class="item"><a href="/anime/genre/82/Urban_Fantasy" title="Urban Fantasy">Urban Fantasy</a></span></div></div>
 </div>
 <div class="information">
 <div class="information-item scormem">
 <div class="scormem-container">
 <div class="scormem-item score score-label score-8" title="Score">
 <i class="fa-regular fa-star mr4"></i>8.27
         </div>
 <div class="scormem-item member" title="Members">
 <i class="fa-solid fa-user mr4"></i>819K
         </div>
 </div>
 </div>
 <div class="information-item buttons">
 <a class="Lightbox_AddEdit button_add ga-click btn-anime-watch-status js-anime-watch-status button notinmylist addtolist" href="https://myanimelist.net/ownlist/anime/add?selected_series_id=52299&amp;hideLayout=1&amp;click_type=list-add-anime-seasonal-add-to-my-list"><span class="ga-click ga-impression" data-ga-click-param="aid:52299" data-ga-click-type="list-add-anime-seasonal-add-to-my-list" data-ga-impression-type="list-add-anime-seasonal-add-to-my-list" data-status="0" data-work-type="anime" style="line-height: unset;">Add to My List</span></a>
 </div>
 </div>
 </div>,
 <div class="js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-1" data-broadcast-available="1" data-genre="8,41,40,23">
 <div>
 <div class="title"><div class="title-text">
 <h2 class="h2_anime_title"><a class="link-title" href="https://myanimelist.net/anime/51180/Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e_3rd_Season">Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 3rd Season</a></h2></div>
 <span class="js-members" style="display: none;">435826</span>
 <span class="js-score" style="display: none;">7.96</span>
 <span class="js-start_date" style="display: none;">20240103</span>
 <span class="js-title" style="display: none;">Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 3rd Season</span>
 </div>
 <div class="prodsrc">
 <div class="video"><a class="ga-click" href="https://myanimelist.net/anime/51180/Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e_3rd_Season/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a> </div>
 <div class="info"><span class="item">Jan 3, 2024</span><span class="item">
 <span>13 eps</span>,
           <span>23 min </span>
 </span>
 </div>
 <div class="broadcast"><a class="js-broadcast-button ga-click" data-ga-click-param="aid:51180" data-ga-click-type="broadcast-tile-streaming-icon" data-raw='{"data":[{"platform":{"id":1,"name":"Crunchyroll","icon":"crunchyroll","type":1},"available":true,"url":"http:\/\/www.crunchyroll.com\/series-273743"},{"platform":{"id":13,"name":"Aniplus TV","icon":"aniplustv","type":2},"available":false,"url":"http:\/\/www.aniplustv.com\/"},{"platform":{"id":16,"name":"Bahamut Anime Crazy","icon":"bahamutanimecrazy","type":2},"available":false,"url":"https:\/\/ani.gamer.com.tw\/"},{"platform":{"id":18,"name":"Bilibili Global","icon":"bilibiliintl","type":2},"available":true,"url":"https:\/\/www.bilibili.tv\/en\/index"},{"platform":{"id":25,"name":"Muse Asia","icon":"museasia","type":2},"available":true,"url":"https:\/\/www.youtube.com\/channel\/UCGbshtvS9t-8CW11W7TooQg"},{"platform":{"id":23,"name":"iQIYI","icon":"iqiyi","type":2},"available":true,"url":"https:\/\/www.iq.com\/"}],"count":{"available":4,"typicals":1,"others":5,"total":6}}' data-subtitle="" data-title="Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 3rd Season" href="javascript:void(0)" onclick="return false;"><i class="malicon malicon-streaming"></i></a> <a class="broadcast-item ga-click" data-available="1" data-ga-click-param="aid:51180" data-ga-click-type="broadcast-tile-streaming-platforms" href="http://www.crunchyroll.com/series-273743" title="Crunchyroll"><i class="spicon spicon-crunchyroll"></i></a></div>
 </div>
 <div class="genres js-genre" id="51180">
 <div class="genres-inner js-genre-inner"><span class="genre">
 <a href="/anime/genre/8/Drama" title="Drama">Drama</a>
 </span><span class="genre">
 <a href="/anime/genre/41/Suspense" title="Suspense">Suspense</a>
 </span></div>
 </div>
 </div>
 <div class="image"><a href="https://myanimelist.net/anime/51180/Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e_3rd_Season"><img alt="Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 3rd Season" src="https://cdn.myanimelist.net/images/anime/1332/139318.jpg" srcset="https://cdn.myanimelist.net/images/anime/1332/139318.jpg 1x, https://cdn.myanimelist.net/images/anime/1332/139318.jpg 2x" width="167"/></a> <a class="link-image" href="https://myanimelist.net/anime/51180/Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e_3rd_Season">Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 3rd Season</a>
 </div>
 <div class="synopsis js-synopsis">
 <p class="preline">Third season of Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e.</p>
 <button class="js-toggle-text toggle-text" style="display: block; margin: 0 auto; background: none; border: none;">
 <i class="fa-solid fa-angle-down" style="pointer-events: none;"></i>
 </button>
 <div class="properties">
 <div class="property">
 <span class="caption">Studio</span><span class="item"><a href="/anime/producer/456/Lerche" title="Lerche">Lerche</a></span></div>
 <div class="property">
 <span class="caption">Source</span><span class="item">Light novel</span>
 </div><div class="property">
 <span class="caption">Themes</span><span class="item"><a href="/anime/genre/40/Psychological" title="Psychological">Psychological</a></span><span class="item"><a href="/anime/genre/23/School" title="School">School</a></span></div></div>
 </div>
 <div class="information">
 <div class="information-item scormem">
 <div class="scormem-container">
 <div class="scormem-item score score-label score-7" title="Score">
 <i class="fa-regular fa-star mr4"></i>7.96
         </div>
 <div class="scormem-item member" title="Members">
 <i class="fa-solid fa-user mr4"></i>436K
         </div>
 </div>
 </div>
 <div class="information-item buttons">
 <a class="Lightbox_AddEdit button_add ga-click btn-anime-watch-status js-anime-watch-status button notinmylist addtolist" href="https://myanimelist.net/ownlist/anime/add?selected_series_id=51180&amp;hideLayout=1&amp;click_type=list-add-anime-seasonal-add-to-my-list"><span class="ga-click ga-impression" data-ga-click-param="aid:51180" data-ga-click-type="list-add-anime-seasonal-add-to-my-list" data-ga-impression-type="list-add-anime-seasonal-add-to-my-list" data-status="0" data-work-type="anime" style="line-height: unset;">Add to My List</span></a>
 </div>
 </div>
 </div>,
 <div class="js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-1" data-broadcast-available="1" data-genre="2,4,10,47,42">
 <div>
 <div class="title"><div class="title-text">
 <h2 class="h2_anime_title"><a class="link-title" href="https://myanimelist.net/anime/52701/Dungeon_Meshi">Dungeon Meshi</a></h2></div>
 <span class="js-members" style="display: none;">422446</span>
 <span class="js-score" style="display: none;">8.61</span>
 <span class="js-start_date" style="display: none;">20240104</span>
 <span class="js-title" style="display: none;">Dungeon Meshi</span>
 </div>
 <div class="prodsrc">
 <div class="video"><a class="ga-click" href="https://myanimelist.net/anime/52701/Dungeon_Meshi/video" title="Watch Promotional Video"><i class="malicon malicon-movie-pv"></i></a> </div>
 <div class="info"><span class="item">Jan 4, 2024</span><span class="item">
 <span>24 eps</span>,
           <span>25 min </span>
 </span>
 </div>
 <div class="broadcast"><a class="js-broadcast-button ga-click" data-ga-click-param="aid:52701" data-ga-click-type="broadcast-tile-streaming-icon" data-raw='{"data":[{"platform":{"id":2,"name":"Netflix","icon":"netflix","type":1},"available":true,"url":"https:\/\/www.netflix.com\/"}],"count":{"available":1,"typicals":1,"others":0,"total":1}}' data-subtitle="" data-title="Dungeon Meshi" href="javascript:void(0)" onclick="return false;"><i class="malicon malicon-streaming"></i></a> <a class="broadcast-item ga-click" data-available="1" data-ga-click-param="aid:52701" data-ga-click-type="broadcast-tile-streaming-platforms" href="https://www.netflix.com/" title="Netflix"><i class="spicon spicon-netflix"></i></a></div>
 </div>
 <div class="genres js-genre" id="52701">
 <div class="genres-inner js-genre-inner"><span class="genre">
 <a href="/anime/genre/2/Adventure" title="Adventure">Adventure</a>
 </span><span class="genre">
 <a href="/anime/genre/4/Comedy" title="Comedy">Comedy</a>
 </span><span class="genre">
 <a href="/anime/genre/10/Fantasy" title="Fantasy">Fantasy</a>
 </span><span class="genre">
 <a href="/anime/genre/47/Gourmet" title="Gourmet">Gourmet</a>
 </span></div>
 </div>
 </div>
 <div class="image"><a href="https://myanimelist.net/anime/52701/Dungeon_Meshi"><img alt="Dungeon Meshi" src="https://cdn.myanimelist.net/images/anime/1711/142478.jpg" srcset="https://cdn.myanimelist.net/images/anime/1711/142478.jpg 1x, https://cdn.myanimelist.net/images/anime/1711/142478.jpg 2x" width="167"/></a> <a class="link-image" href="https://myanimelist.net/anime/52701/Dungeon_Meshi">Dungeon Meshi</a>
 </div>
 <div class="synopsis js-synopsis">
 <p class="preline">Adventuring knight Laios Touden leads a small party through a seemingly endless dungeon, a subterranean maze full of dangerous monsters and precarious traps. Through the use of advanced magic, an explorer can sometimes be resurrected, allowing them to learn from past mistakes and give traversing the dungeon another go. However, when a powerful dragon eats Falin, Laios' spellcasting sister, she sends her brother and his companions back to the beginning to save them from permanent ends.

 Though strapped for cash and equipment, Laios resolves to fight his way through the dungeon and rescue Falin before she can be digested by the dragon. Despite some of Laios' allies abandoning him, two remain by his side: elven mage Marcille Donato and halfling locksmith Chilchuck Tims. Due to their lack of funds, the party faces the daunting prospect of starving before being able to complete their quest. However, they find salvation in Senshi, a dwarven warrior with a penchant for cooking and safely eating defeated monsters.

 With Senshi's culinary expertise, Laios and his companions struggle through the dungeon while learning about gourmet dining—and each other—along the way.

 [Written by MAL Rewrite]</p>
 <button class="js-toggle-text toggle-text" style="display: block; margin: 0 auto; background: none; border: none;">
 <i class="fa-solid fa-angle-down" style="pointer-events: none;"></i>
 </button>
 <div class="properties">
 <div class="property">
 <span class="caption">Studio</span><span class="item"><a href="/anime/producer/803/Trigger" title="Trigger">Trigger</a></span></div>
 <div class="property">
 <span class="caption">Source</span><span class="item">Manga</span>
 </div><div class="property">
 <span class="caption">Demographic</span><span class="item"><a href="/anime/genre/42/Seinen" title="Seinen">Seinen</a></span></div></div>
 </div>
 <div class="information">
 <div class="information-item scormem">
 <div class="scormem-container">
 <div class="scormem-item score score-label score-8" title="Score">
 <i class="fa-regular fa-star mr4"></i>8.61
         </div>
 <div class="scormem-item member" title="Members">
 <i class="fa-solid fa-user mr4"></i>422K
         </div>
 </div>
 </div>
 <div class="information-item buttons">
 <a class="Lightbox_AddEdit button_add ga-click btn-anime-watch-status js-anime-watch-status button notinmylist addtolist" href="https://myanimelist.net/ownlist/anime/add?selected_series_id=52701&amp;hideLayout=1&amp;click_type=list-add-anime-seasonal-add-to-my-list"><span class="ga-click ga-impression" data-ga-click-param="aid:52701" data-ga-click-type="list-add-anime-seasonal-add-to-my-list" data-ga-impression-type="list-add-anime-seasonal-add-to-my-list" data-status="0" data-work-type="anime" style="line-height: unset;">Add to My List</span></a>
 </div>
 </div>
 </div>,
 <div class="js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-1" data-broadcast-available="1" data-genre="1,4,10,57,20,23,27">
 <div>
 <div class="title"><div class="title-text">
 <h2 class="h2_anime_title"><a class="link-title" href="https://myanimelist.net/anime/55813/Mashle__Shinkakusha_Kouho_Senbatsu_Shiken-hen">Mashle: Shinkakusha Kouho Senbatsu Shiken-hen</a></h2></div>
 <span class="js-members" style="display: none;">406377</span>
 <span class="js-score" style="display: none;">7.81</span>
 <span class="js-start_date" style="display: none;">20240106</span>
 <span class="js-title" style="display: none;">Mashle: Shinkakusha Kouho Senbatsu Shiken-hen</span>
 </div>
 <div class="prodsrc">
 <div class="video"><a class="ga-click" href="https://myanimelist.net/anime/55813/Mashle__Shinkakusha_Kouho_Senbatsu_Shiken-hen/video" title="Watch Episode Video"><i class="malicon malicon-movie-episode"></i></a> </div>
 <div class="info"><span class="item">Jan 6, 2024</span><span class="item">
 <span>12 eps</span>,
           <span>23 min </span>
 </span>
 </div>
 <div class="broadcast"><a class="js-broadcast-button ga-click" data-ga-click-param="aid:55813" data-ga-click-type="broadcast-tile-streaming-icon" data-raw='{"data":[{"platform":{"id":1,"name":"Crunchyroll","icon":"crunchyroll","type":1},"available":false,"url":"http:\/\/www.crunchyroll.com\/series-283547"},{"platform":{"id":11,"name":"Ani-One Asia","icon":"ani-oneasia","type":2},"available":true,"url":"https:\/\/www.youtube.com\/channel\/UC0wNSTMWIL3qaorLx0jie6A"},{"platform":{"id":13,"name":"Aniplus TV","icon":"aniplustv","type":2},"available":false,"url":"http:\/\/www.aniplustv.com\/"}],"count":{"available":1,"typicals":1,"others":2,"total":3}}' data-subtitle="" data-title="Mashle: Shinkakusha Kouho Senbatsu Shiken-hen" href="javascript:void(0)" onclick="return false;"><i class="malicon malicon-streaming"></i></a> </div>
 </div>
 <div class="genres js-genre" id="55813">
 <div class="genres-inner js-genre-inner"><span class="genre">
 <a href="/anime/genre/1/Action" title="Action">Action</a>
 </span><span class="genre">
 <a href="/anime/genre/4/Comedy" title="Comedy">Comedy</a>
 </span><span class="genre">
 <a href="/anime/genre/10/Fantasy" title="Fantasy">Fantasy</a>
 </span></div>
 </div>
 </div>

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
anime_raw_data = soup.find_all("div", class_ = "js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-1")

anime_raw_data
```

</details>

---

### **2b**
---

- Kita akan melakukan scrape data dalam satu proses ini
- Untuk informasi - informasi yang ingin kita extract memiliki html tag sebagai berikut:
    - `Title`: `<a>`
    - `Link MAL`: `<span class = "item">`
    - `Release Date`: `<a href=...>`
    - `Anime Episode`: `<div class = "info">`
    - `Anime Duration`: `<div class = "info">`
    - `Anime Genre`: `<div class = "genres-inner js-genre-inner">`
    - `Link Image`: `<img src="...">`
    - `Description`: `<p>`
    - `Studio`: `<div class = "property">`
    - `Source`: `<div class = "property">`
    - `Show Type`: `TV/ONA/OVA/Movie`

- Untuk data `Anime Episode` dan `Anime Duration` memiliki sub-child, yaitu `<span class = "item">` oleh karena itu kita perlu membuat iterasi lagi ketika ingin extract data tersebut
- Untuk data `Anime Genre` memiliki sub-child, yaitu `<a>`
- Lalu, untuk data `Studio` dan `Source` memiliki sub-child yaitu `<div class = "property">`

- Simpan hasil dari scrapping tersebut di tiap iterasi ke dalam bentuk dictionary, setelah itu simpan seluruh data ke dalam satu list

In [208]:
anime_tv_data = []

for data in tqdm(anime_raw_data):

    # give delay 0.05 second in each iteration
    time.sleep(0.05)

    # get title
    title = data.find("a").text

    # get release date
    release_date = data.find("span", class_ = "item").text

    # get link mal
    link_mal = data.find("a").get("href")

    # get all info data like release date, anime minutes, and anime episode
    get_anime_info = data.find("div", class_ = "info")

    # get more detail info
    get_anime_detail_info = get_anime_info.find_all('span', class_='item')

    # get release date
    release_date = get_anime_detail_info[0].text

    # get episode
    anime_episode = get_anime_detail_info[1].contents[1].text

    # get duration
    anime_duration = get_anime_detail_info[1].contents[3].text

    # get genre anime data
    genre_raw = data.find_all("div", class_ = "genres-inner js-genre-inner")

    # Iterate through each <div> and extract genres
    for genre_div in genre_raw:

        genre_links = genre_div.find_all('a')

        # Extract and print genre names
        genres = [link.text for link in genre_links]

    # get img link
    img_link = data.find("img").get("src")

    # get description
    description = data.find("p").text

    # get studio name

    get_studio = data.find_all("div", class_ = "property")[0]

    if get_studio.find("a") is not None:
        studio = get_studio.find("a").text

    else:
        studio = ""

    # get source
    get_source = data.find_all("div", class_ = "property")[1]

    source = get_source.find("span", class_ = "item").text

    dict_data = {
        "title": title,
        "link_mal": link_mal,
        "release_date": release_date,
        "anime_episode": anime_episode,
        "anime_duration": anime_duration,
        "anime_genre": genres,
        "img_link": img_link,
        "description": description,
        "studio": studio,
        "source": source,
        "show_type": "TV"
    }

    anime_tv_data.append(dict_data)

anime_tv_data

  0%|          | 0/87 [00:00<?, ?it/s]

100%|██████████| 87/87 [00:04<00:00, 20.41it/s]

[{'title': 'Ore dake Level Up na Ken',
  'link_mal': 'https://myanimelist.net/anime/52299/Ore_dake_Level_Up_na_Ken',
  'release_date': 'Jan 7, 2024',
  'anime_episode': '12 eps',
  'anime_duration': '23 min ',
  'anime_genre': ['Action', 'Adventure', 'Fantasy'],
  'img_link': 'https://cdn.myanimelist.net/images/anime/1801/142390.jpg',
  'description': 'Humanity was caught at a precipice a decade ago when the first gates—portals linked with other dimensions that harbor monsters immune to conventional weaponry—emerged around the world. Alongside the appearance of the gates, various humans were transformed into hunters and bestowed superhuman abilities. Responsible for entering the gates and clearing the dungeons within, many hunters chose to form guilds to secure their livelihoods.\r\n\r\nSung Jin-Woo is an E-rank hunter dubbed as the weakest hunter of all mankind. While exploring a supposedly safe dungeon, he and his party encounter an unusual tunnel leading to a deeper area. Enticed by the prospect of treasure, the group presses forward, only to be confronted with horrors beyond their imagination. Miraculously, Jin-Woo survives the incident and soon finds that he now has access to an interface visible only to him. This mysterious system promises him the power he has long dreamed of—but everything comes at a price.\r\n\r\n[Written by MAL Rewrite]',
  'studio': 'A-1 Pictures',
  'source': 'Web manga',
  'show_type': 'TV'},
 {'title': 'Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 3rd Season',
  'link_mal': 'https://myanimelist.net/anime/51180/Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e_3rd_Season',
  'release_date': 'Jan 3, 2024',
  'anime_episode': '13 eps',
  'anime_duration': '23 min ',
  'anime_genre': ['Drama', 'Suspense'],
  'img_link': 'https://cdn.myanimelist.net/images/anime/1332/139318.jpg',
  'description': 'Third season of Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e.',
  'studio': 'Lerche',
  'source': 'Light novel',
  'show_type': 'TV'},
 {'title': 'Dungeon Meshi',
  'link_mal': 'https://myanimelist.net/anime/52701/Dungeon_Meshi',
  'release_date': 'Jan 4, 2024',
  'anime_episode': '24 eps',
  'anime_duration': '25 min ',
  'anime_genre': ['Adventure', 'Comedy', 'Fantasy', 'Gourmet'],
  'img_link': 'https://cdn.myanimelist.net/images/anime/1711/142478.jpg',
  'description': "Adventuring knight Laios Touden leads a small party through a seemingly endless dungeon, a subterranean maze full of dangerous monsters and precarious traps. Through the use of advanced magic, an explorer can sometimes be resurrected, allowing them to learn from past mistakes and give traversing the dungeon another go. However, when a powerful dragon eats Falin, Laios' spellcasting sister, she sends her brother and his companions back to the beginning to save them from permanent ends.\r\n\r\nThough strapped for cash and equipment, Laios resolves to fight his way through the dungeon and rescue Falin before she can be digested by the dragon. Despite some of Laios' allies abandoning him, two remain by his side: elven mage Marcille Donato and halfling locksmith Chilchuck Tims. Due to their lack of funds, the party faces the daunting prospect of starving before being able to complete their quest. However, they find salvation in Senshi, a dwarven warrior with a penchant for cooking and safely eating defeated monsters.\r\n\r\nWith Senshi's culinary expertise, Laios and his companions struggle through the dungeon while learning about gourmet dining—and each other—along the way.\r\n\r\n[Written by MAL Rewrite]",
  'studio': 'Trigger',
  'source': 'Manga',
  'show_type': 'TV'},
 {'title': 'Mashle: Shinkakusha Kouho Senbatsu Shiken-hen',
  'link_mal': 'https://myanimelist.net/anime/55813/Mashle__Shinkakusha_Kouho_Senbatsu_Shiken-hen',
  'release_date': 'Jan 6, 2024',
  'anime_episode': '12 eps',
  'anime_duration': '23 min ',
  'anime_genre': ['Action', 'Comedy', 'Fantasy'],
  'img_link': 'https://cdn.myanimelist.net/images/anime/1912/140804.jpg',
  'description': "After Mash Burnedead's clash with Magia Lupus, the secret about his powers is now out in the open. The short-lived celebration ends when the Bureau of Magic summons Mash before an audience of Divine Visionaries, who collectively decree Mash should reap the consequences and die. However, an evil shadow organization called Innocent Zero hijacks the inquiry to demand that Mash be kept alive.\r\n\r\nMash proves that he is capable of dealing with Innocent Zero, but the Divine Visionaries' verdict remains unchanged. Luckily, Mash finds unexpected allies in Divine Visionary Rayne Ames and Headmaster Wahlberg Baigan, and they successfully defer his execution until Innocent Zero is defeated. Mash is now allowed to live under one condition: he must be selected as the Divine Visionary candidate by the year's end.\r\n\r\n[Written by MAL Rewrite]",
  'studio': 'A-1 Pictures',
  'source': 'Manga',
  'show_type': 'TV'},
 {'title': 'Tsuki ga Michibiku Isekai Douchuu 2nd Season',
  'link_mal': 'https://myanimelist.net/anime/49889/Tsuki_ga_Michibiku_Isekai_Douchuu_2nd_Season',
  'release_date': 'Jan 8, 2024',
  'anime_episode': '25 eps',
  'anime_duration': '23 min ',
  'anime_genre': ['Action', 'Adventure', 'Comedy', 'Fantasy'],
  'img_link': 'https://cdn.myanimelist.net/images/anime/1794/142621.jpg',
  'description': "Despite a rough start, Makoto Misumi's life in another world takes a positive turn when he meets more demihumans who recognize his presence. Now as the leader of a fast-growing demihuman community, Makoto wishes to make human society more accepting of them and thus builds a business showcasing the demihumans' abilities. To extend his reach further, Makoto enrolls at the Rotsgard Academy to learn magic and expand his business venture there.\r\n\r\nMeanwhile, the goddess who summoned and forsaken Makoto had brought two other people to her world shortly after sending him away, making them heroes of their respective nations. Given enough time, Makoto's path will intertwine with both of these heroes, which may cause the world to take a drastic direction.\r\n\r\n[Written by MAL Rewrite]",
  'studio': 'J.C.Staff',
  'source': 'Light novel',
  'show_type': 'TV'},
 {'title': 'Yubisaki to Renren',
  'link_mal': 'https://myanimelist.net/anime/55866/Yubisaki_to_Renren',
  'release_date': 'Jan 6, 2024',
  'anime_episode': '12 eps',
  'anime_duration': '23 min ',
  'anime_genre': ['Romance'],
  'img_link': 'https://cdn.myanimelist.net/images/anime/1478/140828.jpg',
  'description': "For hearing-impaired university student Yuki Itose, silence has been a natural part of life since birth. Her world is small and isolated; she commutes to campus, interacts with her best friend Rin Fujishiro, and communicates through writing and text messages—a lifestyle that offers little to no change. One day, during her commute, Yuki meets fellow student Itsuomi Nagi, a multilingual travel enthusiast and friend of Rin. When Itsuomi learns of Yuki's condition, he takes it in stride, moving Yuki's heart. From this one simple gesture, Yuki and Itsuomi's lives start changing day by day as they let each other into their own worlds.\r\n\r\n[Written by MAL Rewrite]",
  'studio': 'Ajia-do',
  'source': 'Manga',
  'show_type': 'TV'},
 {'title': 'Chiyu Mahou no Machigatta Tsukaikata',
  'link_mal': 'https://myanimelist.net/anime/49613/Chiyu_Mahou_no_Machigatta_Tsukaikata',
  'release_date': 'Jan 6, 2024',
  'anime_episode': '13 eps',
  'anime_duration': '23 min ',
  'anime_genre': ['Action', 'Adventure', 'Fantasy'],
  'img_link': 'https://cdn.myanimelist.net/images/anime/1733/140802.jpg',
  'description': "Ken Usato, an ordinary high schooler, wishes for something fantastical to occur in his unremarkable life. Such an opportunity arrives when he is transported to another world alongside Kazuki Ryuusen and Suzune Inukami, two prodigious members of his school's student council. Arriving in Llinger Kingdom, the three are deemed to be the heroes tasked with stopping the impending invasion by the Demon Lord's army. However, this is a misunderstanding—Usato was summoned by accident and, unlike his two friends, is not one of the heroes.\r\n\r\nDespite this disheartening revelation, Usato learns that he has an aptitude for the extremely rare healing magic. This catches the attention of Rose, the intimidating captain of the kingdom's Rescue Team, who forcibly takes custody of Usato to mold him into a full-fledged healer. As he undergoes grueling training under Rose's supervision, Usato resolves to become capable enough to protect his friends from the dangers of this world.\r\n\r\n[Written by MAL Rewrite]",
  'studio': 'Shin-Ei Animation',
  'source': 'Light novel',
  'show_type': 'TV'},
 {'title': 'Boku no Kokoro no Yabai Yatsu 2nd Season',
  'link_mal': 'https://myanimelist.net/anime/55690/Boku_no_Kokoro_no_Yabai_Yatsu_2nd_Season',
  'release_date': 'Jan 7, 2024',
  'anime_episode': '13 eps',
  'anime_duration': '23 min ',
  'anime_genre': ['Comedy', 'Romance'],
  'img_link': 'https://cdn.myanimelist.net/images/anime/1643/138581.jpg',
  'description': 'After an eventful winter break, Kyoutarou Ichikawa and Anna Yamada reunite with a stronger bond. They continue to grow in their own ways, with Yamada taking on more challenging photoshoots and Ichikawa maturing both physically and emotionally as he tackles his affections for Yamada. However, spending time together outside of school allows for their relationship to deepen, and it becomes increasingly difficult to deny their budding romantic feelings.\r\n\r\nGrappling with these unexpected and new emotions, Ichikawa and Yamada realize that, with the passage of time, their relationship is bound to change—and they must ultimately decide whether they wish to remain close friends or finally become a couple.\r\n\r\n[Written by MAL Rewrite]',
  'studio': 'Shin-Ei Animation',
  'source': 'Manga',
  'show_type': 'TV'},
 {'title': 'Mato Seihei no Slave',
  'link_mal': 'https://myanimelist.net/anime/50392/Mato_Seihei_no_Slave',
  'release_date': 'Jan 4, 2024',
  'anime_episode': '12 eps',
  'anime_duration': '23 min ',
  'anime_genre': ['Action', 'Fantasy', 'Ecchi'],
  'img_link': 'https://cdn.myanimelist.net/images/anime/1114/140805.jpg',
  'description': 'As his school days draw to an end, Yuuki Wakura worries about his future. While lamenting the prospect of living an ordinary life, he is suddenly drawn into the world of Mato: an alternate dimension filled with dangerous monsters called Shuuki. Over the years since the existence of Mato was first confirmed, incidents of people accidentally wandering into the other world have become commonplace. To combat the threat of the Shuuki and rescue victims like Yuuki, the all-female Demon Defense Force was established. Its members have been blessed with the power of "Peaches"—Mato fruits that grant supernatural abilities only to women.\r\n\r\nThough Yuuki\'s situation is dire, he is saved in the nick of time by Kyouka Uzen, the chief of the Demon Defense Force\'s seventh unit. Despite Kyouka\'s impeccable skills in battle, she has long been held back by her Peach-granted ability, Slave. Slave allows Kyouka to put a living being under her control and draw out its strength, but the Shuuki that she had enslaved until now had all proven to be exceedingly weak.\r\n\r\nWhen Yuuki and Kyouka become surrounded by a horde of Shuuki, Kyouka resorts to something she has never tried before: using her ability on a man. To her surprise, Yuuki\'s slave form is much more powerful than she could have imagined. Believing the young man to be the key to unlocking her true potential, Kyouka invites Yuuki to join the Demon Defense Force—but not as a regular member.\r\n\r\n[Written by MAL Rewrite]',
  'studio': 'Seven Arcs',
  'source': 'Manga',
  'show_type': 'TV'},
 {'title': 'Loop 7-kaime no Akuyaku Reijou wa, Moto Tekikoku de Jiyuu Kimama na Hanayome Seikatsu wo Mankitsu suru',
  'link_mal': 'https://myanimelist.net/anime/56352/Loop_7-kaime_no_Akuyaku_Reijou_wa_Moto_Tekikoku_de_Jiyuu_Kimama_na_Hanayome_Seikatsu_wo_Mankitsu_suru',
  'release_date': 'Jan 7, 2024',
  'anime_episode': '12 eps',
  'anime_duration': '23 min ',
  'anime_genre': ['Romance'],
  'img_link': 'https://cdn.myanimelist.net/images/anime/1533/140617.jpg',
  'description': "Rishe Irmgard Weitzner finds herself in a familiar situation: her fiancé is publicly breaking off their engagement, and her ducal family is about to disown her in shame. However, Rishe is not distraught; she has already had six chances to rebuild her life and chase a different passion each time. But she would always get swept up in a war and die, so now she wishes for her seventh reincarnation to be easygoing and uneventful.\r\n\r\nWhat Rishe does not take into account is the presence of Arnold Hein, the crown prince of the Galkhein Kingdom. He is destined to usurp the throne and become a tyrant who starts a large-scale invasion of neighboring countries. To make their encounter worse, Arnold is the one who killed Rishe in her previous life. That is why it is all the more shocking when he proposes to Rishe on the spot. In pursuit of her desired life, Rishe must consider accepting Arnold's proposal and discover the reasons behind his brutal actions to stop the war from ever happening.\r\n\r\n[Written by MAL Rewrite]",
  'studio': 'HORNETS',
  'source': 'Light novel',
  'show_type': 'TV'},
 {'title': 'Dosanko Gal wa Namara Menkoi',
  'link_mal': 'https://myanimelist.net/anime/53421/Dosanko_Gal_wa_Namara_Menkoi',
  'release_date': 'Jan 9, 2024',
  'anime_episode': '12 eps',
  'anime_duration': '24 min ',
  'anime_genre': ['Comedy', 'Romance'],
  'img_link': 'https://cdn.myanimelist.net/images/anime/1937/136906.jpg',
  'description': "Having just moved from Tokyo to Hokkaido, high school student Tsubasa Shiki decides to explore the picturesque winter landscape he could never experience in the nation's capital. It only takes a moment for Tsubasa's idealized view of Japan's northernmost prefecture to crumble, as the sheer cold and frigid air quickly overwhelm him. While trying to find the way to his new home, Tsubasa runs into Minami Fuyuki—a talkative and friendly Hokkaido native who, despite the cold, is wearing a short skirt. The girl wastes no time in striking up a conversation, and Tsubasa comes to realize that the winter weather is not all that is too much for him to handle.\r\n\r\nThe next day, Tsubasa is shocked to learn that not only is Fuyuki in his class, but her seat is also right next to his. Swept along by Fuyuki's persistent advances, the young man soon becomes captivated by both life in Hokkaido and the beautiful girl determined to get closer to him. As he deepens his relationship with Fuyuki and meets other fashionable girls from his school, Tsubasa finds out that Hokkaido gals truly are adorable.\r\n\r\n[Written by MAL Rewrite]",
  'studio': 'Blade',
  'source': 'Manga',
  'show_type': 'TV'},
 {'title': 'Ninja Kamui',
  'link_mal': 'https://myanimelist.net/anime/56285/Ninja_Kamui',
  'release_date': 'Feb 11, 2024',
  'anime_episode': '13 eps',
  'anime_duration': '23 min ',
  'anime_genre': ['Action', 'Sci-Fi'],
  'img_link': 'https://cdn.myanimelist.net/images/anime/1142/141351.jpg',
  'description': "Seemingly an average man, Joe Logan leads a peaceful life in the countryside with his wife and child. However, the Logan family have actually assumed false identities to escape from Joe's past as a fearsome ninja assassin. Despite a string of high-profile murders of his former peers, Joe is sure that his new life is secure—but his tranquil bliss is soon shattered when his family is slaughtered by members of his former clan.\r\n\r\nLeft for dead, Joe wakes up in a hospital, unsure of how he survived the wounds that should have killed him. Police detectives Emma Samanda and Mike Moriss, assigned to investigate the Logan family's deaths, witness another attempt on Joe's life. However, this time Joe is prepared. Unleashing secret techniques, he easily dispatches his enemies, shedding his new identity in the process.\r\n\r\nEmbracing his old ways, Joe shrouds himself in his former persona, cutting through the organization he once served in the name of cold-blooded revenge. Assisted in his hunt by the detective duo, Joe will stop at nothing to kill his past and the demons hailing from it.\r\n\r\n[Written by MAL Rewrite]",
  'studio': 'E&H Production',
  'source': 'Original',
  'show_type': 'TV'},
 {'title': 'Nozomanu Fushi no Boukensha',
  'link_mal': 'https://myanimelist.net/anime/51648/Nozomanu_Fushi_no_Boukensha',
  'release_date': 'Jan 8, 2024',
  'anime_episode': '12 eps',
  'anime_duration': '23 min ',
  'anime_genre': ['Action', 'Adventure', 'Fantasy'],
  'img_link': None,
  'description': 'While exploring a labyrinth, Rentt Faina, an adventurer with lots of experience but little to show for it, is killed by a dragon upon discovering its lair. Shockingly, he wakes up to find himself turned into a skeleton, the lowest class of undead monsters. As Rentt fights against the other monsters of the labyrinth, he discovers that slaying them gains him experience towards higher stages of undead evolution—even ones with flesh! With this revelation in hand, Rentt obtains a new objective in his undeath: keep evolving in the hope of eventually becoming a vampire, the highest form of undead that is nearly indistinguishable from human beings.\r\n\r\nDespite being forced to hide his past identity and monstrous nature under an unremovable mask, Rentt manages to return to a semblance of his former life. Granted shelter by Lorraine Vivier, an elite researcher and retired adventurer, Rentt assumes her surname and starts over from scratch as a rookie. Determined to pursue his childhood dream and become a mithril-class adventurer, Rentt must be cautious not to disclose his new bodily circumstances, lest the adventurers’ guild seek to exterminate the monster he has become.\r\n\r\n[Written by MAL Rewrite]',
  'studio': 'Connect',
  'source': 'Light novel',
  'show_type': 'TV'},
 {'title': 'Mahou Shoujo ni Akogarete',
  'link_mal': 'https://myanimelist.net/anime/54722/Mahou_Shoujo_ni_Akogarete',
  'release_date': 'Jan 3, 2024',
  'anime_episode': '13 eps',
  'anime_duration': '23 min ',
  'anime_genre': ['Action', 'Comedy', 'Girls Love', 'Ecchi'],
  'img_link': None,
  'description': 'A team of three magical girls known as Tres Magia protects the town where Utena Hiiragi lives. Like many others, Utena loves these magical girls who valiantly fight in the name of justice. One day, a mysterious black mascot character appears before Utena and grants her the opportunity of a lifetime: a chance to transform into a magical girl.\r\n\r\nHowever, the offer is not what it seems, as Utena has been recruited for an evil organization to fight the magical girls she has always admired. Utena is then forced to confront Tres Magia in battle; but instead of feeling remorse, she unexpectedly finds pleasure in inflicting pain on the magical girls. Completely giving in to her desires, Utena embraces her role as a villain, slowly transforming her adoration for magical girls into a new sadistic obsession.\r\n\r\n[Written by MAL Rewrite]',
  'studio': 'Asahi Production',
  'source': 'Web manga',
  'show_type': 'TV'},
 {'title': 'Akuyaku Reijou Level 99: Watashi wa Ura-Boss desu ga Maou dewa Arimasen',
  'link_mal': 'https://myanimelist.net/anime/54837/Akuyaku_Reijou_Level_99__Watashi_wa_Ura-Boss_desu_ga_Maou_dewa_Arimasen',
  'release_date': 'Jan 9, 2024',
  'anime_episode': '12 eps',
  'anime_duration': '23 min ',
  'anime_genre': ['Fantasy'],
  'img_link': None,

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
anime_tv_data = []

for data in tqdm(anime_raw_data):

    # give delay 0.05 second in each iteration
    time.sleep(0.05)

    # get title
    title = data.find("a").text

    # get release date
    release_date = data.find("span", class_ = "item").text

    # get link mal
    link_mal = data.find("a").get("href")

    # get all info data like release date, anime minutes, and anime episode
    get_anime_info = data.find("div", class_ = "info")

    # get more detail info
    get_anime_detail_info = get_anime_info.find_all('span', class_='item')

    # get release date
    release_date = get_anime_detail_info[0].text

    # get episode
    anime_episode = get_anime_detail_info[1].contents[1].text

    # get duration
    anime_duration = get_anime_detail_info[1].contents[3].text

    # get genre anime data
    genre_raw = data.find_all("div", class_ = "genres-inner js-genre-inner")

    # Iterate through each <div> and extract genres
    for genre_div in genre_raw:

        genre_links = genre_div.find_all('a')

        # Extract and print genre names
        genres = [link.text for link in genre_links]

    # get img link
    img_link = data.find("img").get("src")

    # get description
    description = data.find("p").text

    # get studio name

    get_studio = data.find_all("div", class_ = "property")[0]

    if get_studio.find("a") is not None:
        studio = get_studio.find("a").text

    else:
        studio = ""

    # get source
    get_source = data.find_all("div", class_ = "property")[1]

    source = get_source.find("span", class_ = "item").text

    dict_data = {
        "title": title,
        "link_mal": link_mal,
        "release_date": release_date,
        "anime_episode": anime_episode,
        "anime_duration": anime_duration,
        "anime_genre": genres,
        "img_link": img_link,
        "description": description,
        "studio": studio,
        "source": source,
        "show_type": "TV"
    }

    anime_tv_data.append(dict_data)

anime_tv_data
```

</details>

---

### **2c**
---

Setelah itu, kita ubah data tersebut ke dalam bentuk DataFrame

In [209]:
anime_tv_data = pd.DataFrame(anime_tv_data)

anime_tv_data.head()

,title,link_mal,release_date,anime_episode,anime_duration,anime_genre,img_link,description,studio,source,show_type
0,Ore dake Level Up na Ken,https://myanimelist.net/anime/52299/Ore_dake_L...,"Jan 7, 2024",12 eps,23 min,"[Action, Adventure, Fantasy]",https://cdn.myanimelist.net/images/anime/1801/...,Humanity was caught at a precipice a decade ag...,A-1 Pictures,Web manga,TV
1,Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu ...,https://myanimelist.net/anime/51180/Youkoso_Ji...,"Jan 3, 2024",13 eps,23 min,"[Drama, Suspense]",https://cdn.myanimelist.net/images/anime/1332/...,Third season of Youkoso Jitsuryoku Shijou Shug...,Lerche,Light novel,TV
2,Dungeon Meshi,https://myanimelist.net/anime/52701/Dungeon_Meshi,"Jan 4, 2024",24 eps,25 min,"[Adventure, Comedy, Fantasy, Gourmet]",https://cdn.myanimelist.net/images/anime/1711/...,Adventuring knight Laios Touden leads a small ...,Trigger,Manga,TV
3,Mashle: Shinkakusha Kouho Senbatsu Shiken-hen,https://myanimelist.net/anime/55813/Mashle__Sh...,"Jan 6, 2024",12 eps,23 min,"[Action, Comedy, Fantasy]",https://cdn.myanimelist.net/images/anime/1912/...,"After Mash Burnedead's clash with Magia Lupus,...",A-1 Pictures,Manga,TV
4,Tsuki ga Michibiku Isekai Douchuu 2nd Season,https://myanimelist.net/anime/49889/Tsuki_ga_M...,"Jan 8, 2024",25 eps,23 min,"[Action, Adventure, Comedy, Fantasy]",https://cdn.myanimelist.net/images/anime/1794/...,"Despite a rough start, Makoto Misumi's life in...",J.C.Staff,Light novel,TV

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
anime_tv_data = pd.DataFrame(anime_tv_data)

anime_tv_data.head()
```

</details>

---

## **3**
---

- Kita sudah berhasil melakukan scraping untuk show type `TV`, maka yang belum dilakukan proses scraping adalah show type `ONA`, `OVA`, dan `Movie`
- Kalau kita lihat, ternyata dari ketiga show type itu memiliki struktur html yang sama untuk data - data yang ingin kita scrape
- Untuk membuat proses jauh lebih mudah dan tidak redundan, kita bisa membuat function yang digunakan untuk scrape data berdasarkan html tag dari masing - masing show type
- Gambaran dari function yang ingin kita buat adalah sebagai berikut

    ```python
    def scrape_myanimelist(soup, html_tag, show_type):
        # some process
        ...
    ```

### **3a**
---

- Untuk mempermudah proses scraping, kita bisa membuat scrapper engine yang dimana kita bisa memasukkan parameter seperti `year` dan `season`
- Sehingga proses scraping nanti akan jauh lebih dinamis apabila kita ingin melakukan scraping di tahun yang berbeda dan di season yang berbeda

In [210]:
def init_scrapper_engine(year: int, season: str):
    resp = requests.get(f"https://myanimelist.net/anime/season/{year}/{season}")

    soup = BeautifulSoup(resp.text, "html.parser")

    return soup

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
def init_scrapper_engine(year: int, season: str):
    resp = requests.get(f"https://myanimelist.net/anime/season/{year}/{season}")

    soup = BeautifulSoup(resp.text, "html.parser")

    return soup
```

</details>

---

### **3b**
---

Setelah itu, kita akan membuat function `scrape_myanimelist()` seperti kriteria di atas dan memasukkan code scraping yang kita buat kedalam function tersebut

In [211]:
# code in here
def scrape_myanimelist(soup, html_tag, show_type):

    raw_data = soup.find_all("div", class_ = html_tag)

    anime_data = []

    for data in tqdm(raw_data):

        time.sleep(0.05)

        # get title
        title = data.find("a").text

        # get release date
        release_date = data.find("span", class_ = "item").text

        # get link mal
        link_mal = data.find("a").get("href")

        # get all info data like release date, anime minutes, and anime episode
        get_anime_info = data.find("div", class_ = "info")

        # get more detail info
        get_anime_detail_info = get_anime_info.find_all('span', class_='item')

        # get release date
        release_date = get_anime_detail_info[0].text

        # get episode
        anime_episode = get_anime_detail_info[1].contents[1].text

        # get duration
        anime_duration = get_anime_detail_info[1].contents[3].text

        # get genre anime data
        genre_raw = data.find_all("div", class_ = "genres-inner js-genre-inner")

        # Iterate through each <div> and extract genres
        for genre_div in genre_raw:

            genre_links = genre_div.find_all('a')

            # Extract and print genre names
            genres = [link.text for link in genre_links]

        # get img link
        img_link = data.find("img").get("src")

        # get description
        description = data.find("p").text

        # get studio name

        get_studio = data.find_all("div", class_ = "property")[0]

        if get_studio.find("a") is not None:
            studio = get_studio.find("a").text

        else:
            studio = ""

        # get source
        get_source = data.find_all("div", class_ = "property")[1]

        source = get_source.find("span", class_ = "item").text

        dict_data = {
            "title": title,
            "link_mal": link_mal,
            "release_date": release_date,
            "anime_episode": anime_episode,
            "anime_duration": anime_duration,
            "anime_genre": genres,
            "img_link": img_link,
            "description": description,
            "studio": studio,
            "source": source,
            "show_type": show_type
        }

        anime_data.append(dict_data)

    converted_data = pd.DataFrame(anime_data)

    return converted_data

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
def scrape_myanimelist(soup, html_tag, show_type):

    raw_data = soup.find_all("div", class_ = html_tag)

    anime_data = []

    for data in tqdm(raw_data):

        time.sleep(0.05)

        # get title
        title = data.find("a").text

        # get release date
        release_date = data.find("span", class_ = "item").text

        # get link mal
        link_mal = data.find("a").get("href")

        # get all info data like release date, anime minutes, and anime episode
        get_anime_info = data.find("div", class_ = "info")

        # get more detail info
        get_anime_detail_info = get_anime_info.find_all('span', class_='item')

        # get release date
        release_date = get_anime_detail_info[0].text

        # get episode
        anime_episode = get_anime_detail_info[1].contents[1].text

        # get duration
        anime_duration = get_anime_detail_info[1].contents[3].text

        # get genre anime data
        genre_raw = data.find_all("div", class_ = "genres-inner js-genre-inner")

        # Iterate through each <div> and extract genres
        for genre_div in genre_raw:

            genre_links = genre_div.find_all('a')

            # Extract and print genre names
            genres = [link.text for link in genre_links]

        # get img link
        img_link = data.find("img").get("src")

        # get description
        description = data.find("p").text

        # get studio name

        get_studio = data.find_all("div", class_ = "property")[0]

        if get_studio.find("a") is not None:
            studio = get_studio.find("a").text

        else:
            studio = ""

        # get source
        get_source = data.find_all("div", class_ = "property")[1]

        source = get_source.find("span", class_ = "item").text

        dict_data = {
            "title": title,
            "link_mal": link_mal,
            "release_date": release_date,
            "anime_episode": anime_episode,
            "anime_duration": anime_duration,
            "anime_genre": genres,
            "img_link": img_link,
            "description": description,
            "studio": studio,
            "source": source,
            "show_type": show_type
        }

        anime_data.append(dict_data)

    converted_data = pd.DataFrame(anime_data)

    return converted_data
```

</details>

---

### **3c**
---

- Kita akan coba function yang sudah dibuat untuk melakukan proses scraping website pada sisa show type
- Langkah awal, kita akan inisialisasi BeautifulSoup dengan function `init_scrapper_engine()` yang sudah dibuat

In [218]:
soup = init_scrapper_engine(year = 2024,
                            season = "fall")

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
soup = init_scrapper_engine(year = 2024,
                            season = "winter")
```

</details>

---

Setelah berhasil, kita akan coba scrape pada show type `ONA`

In [213]:
anime_ona_data = scrape_myanimelist(soup = soup,
                                    html_tag = "js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-5",
                                    show_type = "ONA")

anime_ona_data.head()

100%|██████████| 62/62 [00:03<00:00, 18.18it/s]

,title,link_mal,release_date,anime_episode,anime_duration,anime_genre,img_link,description,studio,source,show_type
0,Monsters: Ippyaku Sanjou Hiryuu Jigoku,https://myanimelist.net/anime/56055/Monsters__...,"Jan 22, 2024",1 ep,25 min,[Fantasy],None,A samurai's path leads him to a young waitress...,E&H Production,Manga,ONA
1,Great Pretender: Razbliuto,https://myanimelist.net/anime/57184/Great_Pret...,"Feb 23, 2024",4 eps,22 min,"[Action, Adventure, Mystery]",None,"Presumed dead, master con artist and recoverin...",Wit Studio,Original,ONA
2,Sand Land: The Series,https://myanimelist.net/anime/57160/Sand_Land_...,"Mar 20, 2024",13 eps,24 min,"[Action, Adventure, Fantasy]",None,"In the far future, war has destroyed the entir...",Anima,Manga,ONA
3,Sousou no Frieren: ●● no Mahou,https://myanimelist.net/anime/56885/Sousou_no_...,"Oct 11, 2023",12 eps,1 min,"[Comedy, Fantasy]",None,"Frieren loves collecting peculiar spells, and ...",TOHO animation STUDIO,Manga,ONA
4,Aishang Ta de Liyou Extra,https://myanimelist.net/anime/58143/Aishang_Ta...,"Feb 13, 2024",1 ep,10 min,[Romance],None,(No synopsis yet.),Red Dog Culture House,Web manga,ONA

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
anime_ona_data = scrape_myanimelist(soup = soup,
                                    html_tag = "js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-5",
                                    show_type = "ONA")

anime_ona_data.head()
```

</details>

---

Setelah itu, kita akan scrape sisa show type yang belum di scrape

In [214]:
anime_ova_data = scrape_myanimelist(soup = soup,
                                    html_tag = "js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-2",
                                    show_type = "OVA")

anime_ova_data.head()

100%|██████████| 2/2 [00:00<00:00, 18.05it/s]

,title,link_mal,release_date,anime_episode,anime_duration,anime_genre,img_link,description,studio,source,show_type
0,Watashi no Shiawase na Kekkon: Watashi no Shia...,https://myanimelist.net/anime/55889/Watashi_no...,"Mar 15, 2024",1 ep,23 min,"[Fantasy, Romance]",None,Thirteenth episode of Watashi no Shiawase na K...,Kinema Citrus,Novel,OVA
1,Hajimete no Futarikkiri Ryokou,https://myanimelist.net/anime/57593/Hajimete_n...,"Mar 13, 2024",1 ep,4 min,[],None,A short animation released with the limited ed...,,Music,OVA

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
anime_ova_data = scrape_myanimelist(soup = soup,
                                    html_tag = "js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-2",
                                    show_type = "OVA")

anime_ova_data.head()
```

</details>

---

In [215]:
anime_movie_data = scrape_myanimelist(soup = soup,
                                      html_tag = "js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-3",
                                      show_type = "Movie")

100%|██████████| 18/18 [00:00<00:00, 18.28it/s]

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
anime_movie_data = scrape_myanimelist(soup = soup,
                                      html_tag = "js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-3",
                                      show_type = "Movie")

anime_movie_data.head()
```

</details>

---

## **4**
---

- Kita sudah berhasil melakukan scraping untuk seluruh data show type, tetapi data masih terpisah
- Kita perlu membuat function `concat_anime_data()` untuk menggabungkan empat DataFrame menjadi satu

In [216]:
def concat_anime_data(anime_data):
    concat_data = pd.concat(anime_data)

    return concat_data

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
def concat_anime_data(anime_data):
    concat_data = pd.concat(anime_data)

    return concat_data
```

</details>

---

In [254]:
full_anime_data = concat_anime_data(anime_data = [anime_tv_data, anime_ona_data,
                                                  anime_ova_data, anime_movie_data])

full_anime_data.head()
# 2024 seasonn winter

,title,link_mal,release_date,anime_episode,anime_duration,anime_genre,img_link,description,studio,source,show_type
0,Ore dake Level Up na Ken,https://myanimelist.net/anime/52299/Ore_dake_L...,"Jan 7, 2024",12 eps,23 min,"[Action, Adventure, Fantasy]",https://cdn.myanimelist.net/images/anime/1801/...,Humanity was caught at a precipice a decade ag...,A-1 Pictures,Web manga,TV
1,Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu ...,https://myanimelist.net/anime/51180/Youkoso_Ji...,"Jan 3, 2024",13 eps,23 min,"[Drama, Suspense]",https://cdn.myanimelist.net/images/anime/1332/...,Third season of Youkoso Jitsuryoku Shijou Shug...,Lerche,Light novel,TV
2,Dungeon Meshi,https://myanimelist.net/anime/52701/Dungeon_Meshi,"Jan 4, 2024",24 eps,25 min,"[Adventure, Comedy, Fantasy, Gourmet]",https://cdn.myanimelist.net/images/anime/1711/...,Adventuring knight Laios Touden leads a small ...,Trigger,Manga,TV
3,Mashle: Shinkakusha Kouho Senbatsu Shiken-hen,https://myanimelist.net/anime/55813/Mashle__Sh...,"Jan 6, 2024",12 eps,23 min,"[Action, Comedy, Fantasy]",https://cdn.myanimelist.net/images/anime/1912/...,"After Mash Burnedead's clash with Magia Lupus,...",A-1 Pictures,Manga,TV
4,Tsuki ga Michibiku Isekai Douchuu 2nd Season,https://myanimelist.net/anime/49889/Tsuki_ga_M...,"Jan 8, 2024",25 eps,23 min,"[Action, Adventure, Comedy, Fantasy]",https://cdn.myanimelist.net/images/anime/1794/...,"Despite a rough start, Makoto Misumi's life in...",J.C.Staff,Light novel,TV

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
full_anime_data = concat_anime_data(anime_data = [anime_tv_data, anime_ona_data,
                                                  anime_ova_data, anime_movie_data])

full_anime_data.head()
```

</details>

---

Setelah itu kita simpan data tersebut ke dalam `.csv` dengan filename `full_anime_data_2024_winter.csv`

In [236]:
# code in here
full_anime_data.to_csv("full_anime_data_2024_winter.csv", index = False)

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
full_anime_data.to_csv("full_anime_data_2024_winter.csv", index = False)
```

</details>

---

## **5**
---

- Pada proses ini, kita akan melakukan proses trial and error untuk Transform data sebelum membuat ETL Pipeline
- Langkah - langkah yang akan kita lakukan:
    1. Convert `release_date` menjadi datetime
    2. Kolom `anime_episode` dan `anime_duration` extract numeric value only dan jika tidak ada valuenya ganti dengan value `0`
    3. Split value `anime_genre` tanpa squared bracket

### **5a**
---

Ubah kolom `release_date` menjadi datetime

In [255]:
full_anime_data["release_date"] = pd.to_datetime(full_anime_data["release_date"])

full_anime_data["release_date"]

0    2024-01-07
1    2024-01-03
2    2024-01-04
3    2024-01-06
4    2024-01-08
        ...
13   2024-01-06
14   2024-01-20
15   2024-02-23
16   2024-02-10
17   2024-02-14
Name: release_date, Length: 169, dtype: datetime64[ns]

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
full_anime_data["release_date"] = pd.to_datetime(full_anime_data["release_date"])

full_anime_data["release_date"]
```

</details>

---

### **5b**
---

- Extract numeric value pada kolom `anime_episode` dan `anime_duration`
- Jika ada unknown value seperti `?` kita ubah jadi `0`
- Untuk extract numeric value, kita bisa menggunakan regex `\d+`

In [247]:
full_anime_data["anime_episode"].value_counts()

anime_episode
12 eps     46
1 ep       39
? eps      19
13 eps     16
26 eps      7
24 eps      6
25 eps      3
20 eps      3
16 eps      3
52 eps      2
10 eps      2
4 eps       2
23 eps      2
8 eps       2
18 eps      2
156 eps     2
39 eps      1
28 eps      1
6 eps       1
15 eps      1
76 eps      1
40 eps      1
78 eps      1
50 eps      1
9 eps       1
48 eps      1
30 eps      1
200 eps     1
2 eps       1
Name: count, dtype: int64

In [256]:
full_anime_data["anime_episode"] = full_anime_data["anime_episode"].replace("? eps", 0)

full_anime_data["anime_episode"].value_counts()

anime_episode
12 eps     46
1 ep       39
0          19
13 eps     16
26 eps      7
24 eps      6
25 eps      3
20 eps      3
16 eps      3
52 eps      2
10 eps      2
4 eps       2
23 eps      2
8 eps       2
18 eps      2
156 eps     2
39 eps      1
28 eps      1
6 eps       1
15 eps      1
76 eps      1
40 eps      1
78 eps      1
50 eps      1
9 eps       1
48 eps      1
30 eps      1
200 eps     1
2 eps       1
Name: count, dtype: int64

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
full_anime_data["anime_episode"] = full_anime_data["anime_episode"].replace("? eps", 0)

full_anime_data["anime_episode"].value_counts()
```

</details>

---

In [249]:
full_anime_data["anime_duration"].isnull().sum()

np.int64(0)

Sekarang kita extract value numeric dari kolom `anime_episode` dan `anime_duration`

In [257]:
full_anime_data["anime_episode"] = full_anime_data["anime_episode"].str.extract('(\d+)')

full_anime_data["anime_duration"] = full_anime_data["anime_duration"].str.extract('(\d+)')

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_14066/1720565711.py:1: SyntaxWarning: invalid escape sequence '\d'
  full_anime_data["anime_episode"] = full_anime_data["anime_episode"].str.extract('(\d+)')
/tmp/ipykernel_14066/1720565711.py:3: SyntaxWarning: invalid escape sequence '\d'
  full_anime_data["anime_duration"] = full_anime_data["anime_duration"].str.extract('(\d+)')

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
full_anime_data["anime_episode"] = full_anime_data["anime_episode"].str.extract('(\d+)')

full_anime_data["anime_duration"] = full_anime_data["anime_duration"].str.extract('(\d+)')
```

</details>

---

In [267]:

full_anime_data.loc[1,'anime_genre'].str.capitalize()

1   NaN
1   NaN
1   NaN
1   NaN
Name: anime_genre, dtype: float64

In [259]:
full_anime_data["anime_genre"]

0              [Action, Adventure, Fantasy]
1                         [Drama, Suspense]
2     [Adventure, Comedy, Fantasy, Gourmet]
3                 [Action, Comedy, Fantasy]
4      [Action, Adventure, Comedy, Fantasy]
                      ...
13             [Adventure, Comedy, Fantasy]
14      [Action, Adventure, Drama, Fantasy]
15             [Action, Adventure, Fantasy]
16             [Adventure, Comedy, Fantasy]
17                     [Adventure, Fantasy]
Name: anime_genre, Length: 169, dtype: object

### **5c**
---

Split value `anime_genre` tanpa squared bracket

In [243]:
full_anime_data["anime_genre"] = full_anime_data["anime_genre"].str.replace('[','').replace(']','')

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
      ..
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
Name: anime_genre, Length: 169, dtype: float64

In [244]:
full_anime_data['anime_genre']

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
      ..
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
Name: anime_genre, Length: 169, dtype: float64

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
full_anime_data["anime_genre"] = full_anime_data["anime_genre"].str.strip("[]")

full_anime_data.head().T
```

</details>

---

## **6**
---

- Buatlah Luigi Pipeline dengan menggabungkan Task yang sudah kita lakukan sebelumnya
- Sama seperti di task sebelumnya, kita akan simpan file `csv` pada tiap proses nya

In [268]:
class ExtractAnimeData(luigi.Task):

    year = luigi.IntParameter(default = 2024)
    season = luigi.Parameter(default = "winter")

    def requires(self):
        pass

    def run(self):
        engine_scrapper = init_scrapper_engine(year = self.year,
                                               season = self.season)

        get_anime_tv = scrape_myanimelist(soup = engine_scrapper,
                                          html_tag = "js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-1",
                                          show_type = "TV")

        get_anime_ona = scrape_myanimelist(soup = engine_scrapper,
                                        html_tag = "js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-5",
                                        show_type = "ONA")

        get_anime_ova = scrape_myanimelist(soup = engine_scrapper,
                                        html_tag = "js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-2",
                                        show_type = "OVA")

        get_anime_movie = scrape_myanimelist(soup = engine_scrapper,
                                            html_tag = "js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-3",
                                            show_type = "Movies")

        concat_data = concat_anime_data(anime_data = [get_anime_tv, get_anime_ona,
                                                      get_anime_ova, get_anime_movie])

        concat_data.to_csv(self.output().path, index = False)

    def output(self):
        return luigi.LocalTarget(f"data/raw/extract_anime_{self.year}_{self.season}.csv")

class TransformAnimeData(luigi.Task):

    def requires(self):
        return ExtractAnimeData()

    def run(self):
        transform_anime_data = pd.read_csv(self.input().path)

        transform_anime_data["release_date"] = pd.to_datetime(transform_anime_data["release_date"])

        transform_anime_data["anime_episode"] = transform_anime_data["anime_episode"].replace("? eps", 0)

        transform_anime_data["anime_episode"] = transform_anime_data["anime_episode"].str.extract('(\d+)')

        transform_anime_data["anime_duration"] = transform_anime_data["anime_duration"].str.extract('(\d+)')

        # transform_anime_data["anime_genre"] = transform_anime_data["anime_genre"].str.strip("[]")

        transform_anime_data.to_csv(self.output().path, index = False)

    def output(self):
        return luigi.LocalTarget("data/transform/transform_anime_data.csv")

<>:49: SyntaxWarning: invalid escape sequence '\d'
<>:51: SyntaxWarning: invalid escape sequence '\d'
<>:49: SyntaxWarning: invalid escape sequence '\d'
<>:51: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_14066/345556155.py:49: SyntaxWarning: invalid escape sequence '\d'
  transform_anime_data["anime_episode"] = transform_anime_data["anime_episode"].str.extract('(\d+)')
/tmp/ipykernel_14066/345556155.py:51: SyntaxWarning: invalid escape sequence '\d'
  transform_anime_data["anime_duration"] = transform_anime_data["anime_duration"].str.extract('(\d+)')

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
class ExtractAnimeData(luigi.Task):

    year = luigi.IntParameter(default = 2024)
    season = luigi.Parameter(default = "winter")

    def requires(self):
        pass

    def run(self):
        engine_scrapper = init_scrapper_engine(year = self.year,
                                               season = self.season)

        get_anime_tv = scrape_myanimelist(soup = engine_scrapper,
                                          html_tag = "js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-1",
                                          show_type = "TV")

        get_anime_ona = scrape_myanimelist(soup = engine_scrapper,
                                        html_tag = "js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-5",
                                        show_type = "ONA")

        get_anime_ova = scrape_myanimelist(soup = engine_scrapper,
                                        html_tag = "js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-2",
                                        show_type = "OVA")

        get_anime_movie = scrape_myanimelist(soup = engine_scrapper,
                                            html_tag = "js-anime-category-producer seasonal-anime js-seasonal-anime js-anime-type-all js-anime-type-3",
                                            show_type = "Movies")

        concat_data = concat_anime_data(anime_data = [get_anime_tv, get_anime_ona,
                                                      get_anime_ova, get_anime_movie])

        concat_data.to_csv(self.output().path, index = False)

    def output(self):
        return luigi.LocalTarget(f"live_class_w7/data/raw/extract_anime_{self.year}_{self.season}.csv")

class TransformAnimeData(luigi.Task):

    def requires(self):
        return ExtractAnimeData()

    def run(self):
        transform_anime_data = pd.read_csv(self.input().path)

        transform_anime_data["release_date"] = pd.to_datetime(transform_anime_data["release_date"])

        transform_anime_data["anime_episode"] = transform_anime_data["anime_episode"].replace("? eps", 0)

        transform_anime_data["anime_episode"] = transform_anime_data["anime_episode"].str.extract('(\d+)')

        transform_anime_data["anime_duration"] = transform_anime_data["anime_duration"].str.extract('(\d+)')

        transform_anime_data["anime_genre"] = transform_anime_data["anime_genre"].str.strip("[]")

        transform_anime_data.to_csv(self.output().path, index = False)

    def output(self):
        return luigi.LocalTarget("live_class_w7/data/transform/transform_anime_data.csv")
```

</details>

---

In [271]:
luigi.build([ExtractAnimeData(2024, 'fall'), TransformAnimeData()], local_scheduler = True)

DEBUG: Checking if ExtractAnimeData(year=2024, season=fall) is complete
INFO: Informed scheduler that task   ExtractAnimeData_fall_2024_50f63fa829   has status   PENDING
DEBUG: Checking if TransformAnimeData() is complete
INFO: Informed scheduler that task   TransformAnimeData__99914b932b   has status   DONE
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 14066] Worker Worker(salt=8366570843, workers=1, host=DESKTOP-KIQCHDD, username=rosy, pid=14066) running   ExtractAnimeData(year=2024, season=fall)
100%|██████████| 104/104 [00:05<00:00, 18.09it/s]
100%|██████████| 68/68 [00:03<00:00, 18.17it/s]
0it [00:00, ?it/s]
100%|██████████| 15/15 [00:00<00:00, 18.16it/s]
INFO: [pid 14066] Worker Worker(salt=8366570843, workers=1, host=DESKTOP-KIQCHDD, username=rosy, pid=14066) done      ExtractAnimeData(year=2024, season=fall)
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   ExtractAnimeData_fall_2024_50f63fa829   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO:
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 1 complete ones were encountered:
    - 1 TransformAnimeData()
* 1 ran successfully:
    - 1 ExtractAnimeData(year=2024, season=fall)

This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====

True

## **7**
---

- Pada tahap ini, kita akan melakukan scraping Manga Data menggunakan API
- API yang digunakan adalah https://api.jikan.moe/v4/manga/{id}/full
- Untuk workflow yang digunakan pada task scrape API Manga data ini adalah:
    1. Hit API Manga Data
    2. Select key yang dibutuhkan
    3. Trial and Error terhadap method yang ingin dipakai pada saat proses Transform sebelum membuat ETL Pipeline
    4. Membuat ETL Pipeline

### **7a**
---

- Kita akan coba Hit API dengan salah satu `id` untuk melihat struktur dari data yang dikembalikan oleh API tersebut
- Pada case ini, kita akan coba menggunakan `id` dengan value `1`

Cek status code dari API

In [272]:
resp = requests.get("https://api.jikan.moe/v4/manga/10/full")

resp.status_code

200

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
resp = requests.get("https://api.jikan.moe/v4/manga/1/full")

resp.status_code
```

</details>

---

Sekarang, ambillah data API tersebut dengan format JSON

In [273]:
# code in here
raw_data = resp.json()

raw_data

{'data': {'mal_id': 10,
  'url': 'https://myanimelist.net/manga/10/xxxHOLiC',
  'images': {'jpg': {'image_url': 'https://cdn.myanimelist.net/images/manga/3/217533.jpg',
    'small_image_url': 'https://cdn.myanimelist.net/images/manga/3/217533t.jpg',
    'large_image_url': 'https://cdn.myanimelist.net/images/manga/3/217533l.jpg'},
   'webp': {'image_url': 'https://cdn.myanimelist.net/images/manga/3/217533.webp',
    'small_image_url': 'https://cdn.myanimelist.net/images/manga/3/217533t.webp',
    'large_image_url': 'https://cdn.myanimelist.net/images/manga/3/217533l.webp'}},
  'approved': True,
  'titles': [{'type': 'Default', 'title': 'xxxHOLiC'},
   {'type': 'Synonym', 'title': 'xxxHolic Rou'},
   {'type': 'Synonym', 'title': 'xxxHolic Cage'},
   {'type': 'Japanese', 'title': 'xxxHOLiC'},
   {'type': 'English', 'title': 'xxxHOLiC'}],
  'title': 'xxxHOLiC',
  'title_english': 'xxxHOLiC',
  'title_japanese': 'xxxHOLiC',
  'title_synonyms': ['xxxHolic Rou', 'xxxHolic Cage'],
  'type': 'Manga',
  'chapters': 213,
  'volumes': 19,
  'status': 'Finished',
  'publishing': False,
  'published': {'from': '2003-02-24T00:00:00+00:00',
   'to': '2011-02-09T00:00:00+00:00',
   'prop': {'from': {'day': 24, 'month': 2, 'year': 2003},
    'to': {'day': 9, 'month': 2, 'year': 2011}},
   'string': 'Feb 24, 2003 to Feb 9, 2011'},
  'score': 8.37,
  'scored': 8.37,
  'scored_by': 33107,
  'rank': 237,
  'popularity': 183,
  'members': 86198,
  'favorites': 5073,
  'synopsis': "Living alone after his parents passed away, Kimihiro Watanuki is a high school student who can see otherworldly creatures that are attracted to him. His days are plagued by these nuisances, and he wishes to rid himself of this inconvenience. One fateful day, as Kimihiro is being chased by a horde of spirits, his feet bring him into a mysterious store to seek shelter. Here he meets Yuuko Ichihara, the mistress of this supposed store, who claims to be able to grant wishes. Yuuko offers to grant Kimihiro's, as long as he pays an appropriate price.\n\nThus begins Kimihiro's time working in her store to earn the payment necessary for his wish. In Yuuko's employ, he must become further involved with spirits and the supernatural before he can leave that world behind. How will he fare in the inexplicable encounters that await him?\n\n[Written by MAL Rewrite]",
  'background': 'xxxHOLiC was published in English by Del Rey Manga from April 27, 2004, to February 21, 2012. Kodansha Comics USA republished the series in omnibus volumes from March 18, 2014, to September 8, 2015, with the final two volumes being 2-in-1 while the rest being 3-in-1. It was also published in Spain by Norma Editorial from July 2004 to October 2011; in Brazilian Portuguese by Editora JBC in 38 volumes from March 2006 to October 2011; and in Mexico by Editorial Kamite from October 27, 2018, to April 19, 2024.',
  'authors': [{'mal_id': 1877,
    'type': 'people',
    'name': 'CLAMP',
    'url': 'https://myanimelist.net/people/1877/CLAMP'}],
  'serializations': [{'mal_id': 10,
    'type': 'manga',
    'name': 'Young Magazine (Weekly)',
    'url': 'https://myanimelist.net/manga/magazine/10/Young_Magazine_Weekly'}],
  'genres': [{'mal_id': 4,
    'type': 'manga',
    'name': 'Comedy',
    'url': 'https://myanimelist.net/manga/genre/4/Comedy'},
   {'mal_id': 8,
    'type': 'manga',
    'name': 'Drama',
    'url': 'https://myanimelist.net/manga/genre/8/Drama'},
   {'mal_id': 7,
    'type': 'manga',
    'name': 'Mystery',
    'url': 'https://myanimelist.net/manga/genre/7/Mystery'},
   {'mal_id': 37,
    'type': 'manga',
    'name': 'Supernatural',
    'url': 'https://myanimelist.net/manga/genre/37/Supernatural'}],
  'explicit_genres': [],
  'themes': [],
  'demographics': [{'mal_id': 41,
    'type': 'manga',
    'name': 'Seinen',
    'url': 'https://myanimelist.net/manga/genre/41/Seinen'}],
  'relations': [{'relation': 'Sequel',
    'entry': [{'mal_id': 46010,
      'type': 'manga',
      'name': 'xxxHOLiC: Rei',
      'url': 'https://myanimelist.net/manga/46010/xxxHOLiC__Rei'}]},
   {'relation': 'Adaptation',
    'entry': [{'mal_id': 861,
      'type': 'anime',
      'name': 'xxxHOLiC',
      'url': 'https://myanimelist.net/anime/861/xxxHOLiC'},
     {'mal_id': 3091,
      'type': 'anime',
      'name': 'xxxHOLiC◆Kei',
      'url': 'https://myanimelist.net/anime/3091/xxxHOLiC◆Kei'},
     {'mal_id': 4918,
      'type': 'anime',
      'name': 'xxxHOLiC Shunmuki',
      'url': 'https://myanimelist.net/anime/4918/xxxHOLiC_Shunmuki'},
     {'mal_id': 6864,
      'type': 'anime',
      'name': 'xxxHOLiC Rou',
      'url': 'https://myanimelist.net/anime/6864/xxxHOLiC_Rou'}]},
   {'relation': 'Side Story',
    'entry': [{'mal_id': 10183,
      'type': 'manga',
      'name': 'xxxHOLiC: AnotherHOLiC',
      'url': 'https://myanimelist.net/manga/10183/xxxHOLiC__AnotherHOLiC'}]},
   {'relation': 'Spin-Off',
    'entry': [{'mal_id': 14368,
      'type': 'manga',
      'name': 'Shiritsu Horitsuba Gakuen',
      'url': 'https://myanimelist.net/manga/14368/Shiritsu_Horitsuba_Gakuen'}]},
   {'relation': 'Other',
    'entry': [{'mal_id': 16010,
      'type': 'manga',
      'name': 'K-Dash',
      'url': 'https://myanimelist.net/manga/16010/K-Dash'},
     {'mal_id': 9,
      'type': 'manga',
      'name': 'Tsubasa: RESERVoir CHRoNiCLE',
      'url': 'https://myanimelist.net/manga/9/Tsubasa__RESERVoir_CHRoNiCLE'},
     {'mal_id': 32037,
      'type': 'manga',
      'name': 'Drug & Drop',
      'url': 'https://myanimelist.net/manga/32037/Drug___Drop'}]}],
  'external': [{'name': 'KodanshaKodansha USA',
    'url': 'https://kodansha.us/series/xxxholic-omnibus/'},
   {'name': 'Wikipedia', 'url': 'https://en.wikipedia.org/wiki/XxxHolic'},
   {'name': 'Wikipedia', 'url': 'https://ja.wikipedia.org/wiki/XXXHOLiC'}]}}

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
raw_data = resp.json()

raw_data
```

</details>

---

### **7b**
---

- Jika dilihat, API tersebut mengembalikan banyak sekali informasi
- Maka, langkah selanjutnya adalah kita akan memilih beberapa informasi - informasi saja yang dibutuhkan, seperti:
    - `manga_id`
    - `url_manga`
    - `title`
    - `title_english`
    - `title_japanese`
    - `chapters`
    - `volumes`
    - `status`
    - `start_published`
    - `end_published`
    - `score`
    - `rank`
    - `authors`
    - `genres`
    - `themes`

- Berdasarkan contoh data sebelumnya, kita akan coba extract informasi berdasarkan requirements di atas

In [274]:
manga_data = {
    "manga_id": raw_data["data"]["mal_id"],
    "url_manga": raw_data["data"]["url"],
    "title": raw_data["data"]["title"],
    "title_english": raw_data["data"]["title_english"],
    "title_japanese": raw_data["data"]["title_japanese"],
    "chapters": raw_data["data"]["chapters"],
    "volumes": raw_data["data"]["volumes"],
    "status": raw_data["data"]["status"],
    "start_published": raw_data["data"]["published"]["from"],
    "end_published": raw_data["data"]["published"]["to"],
    "score": raw_data["data"]["score"],
    "rank": raw_data["data"]["rank"],
    "authors": [entry["name"] for entry in raw_data["data"]["authors"]],
    "genres": [entry["name"] for entry in raw_data["data"]["genres"]],
    "themes": [entry["name"] for entry in raw_data["data"]["themes"]]
}

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
manga_data = {
    "manga_id": raw_data["data"]["mal_id"],
    "url_manga": raw_data["data"]["url"],
    "title": raw_data["data"]["title"],
    "title_english": raw_data["data"]["title_english"],
    "title_japanese": raw_data["data"]["title_japanese"],
    "chapters": raw_data["data"]["chapters"],
    "volumes": raw_data["data"]["volumes"],
    "status": raw_data["data"]["status"],
    "start_published": raw_data["data"]["published"]["from"],
    "end_published": raw_data["data"]["published"]["to"],
    "score": raw_data["data"]["score"],
    "rank": raw_data["data"]["rank"],
    "authors": [entry["name"] for entry in raw_data["data"]["authors"]],
    "genres": [entry["name"] for entry in raw_data["data"]["genres"]],
    "themes": [entry["name"] for entry in raw_data["data"]["themes"]]
}
```

</details>

---

In [276]:
pd.DataFrame([manga_data])

,manga_id,url_manga,title,title_english,title_japanese,chapters,volumes,status,start_published,end_published,score,rank,authors,genres,themes
0,10,https://myanimelist.net/manga/10/xxxHOLiC,xxxHOLiC,xxxHOLiC,xxxHOLiC,213,19,Finished,2003-02-24T00:00:00+00:00,2011-02-09T00:00:00+00:00,8.37,237,[CLAMP],"[Comedy, Drama, Mystery, Supernatural]",[]

### **7c**
---

- Setelah berhasil extract data yang kita inginkan, maka langkah selanjutnya adalah mengambil data berdasarkan `id` yang kita inginkan
- Pada case ini, kita akan coba mengambil data sampai `id` 200
- Karena terdapat Rate Limiter pada data API yang ingin kita ambil, maka kita harus berikan delay selama `1 detik` di tiap iterasi

In [277]:
full_data = []

for num_id in tqdm(range(1, 11)):

    resp = requests.get(f"https://api.jikan.moe/v4/manga/{num_id}/full")

    if resp.status_code == 404:
        print(f"Can't get data in id {num_id} because data not available")
        pass

    else:
        raw_data = resp.json()

        manga_data = {
            "manga_id": raw_data["data"]["mal_id"],
            "url_manga": raw_data["data"]["url"],
            "title": raw_data["data"]["title"],
            "title_english": raw_data["data"]["title_english"],
            "title_japanese": raw_data["data"]["title_japanese"],
            "chapters": raw_data["data"]["chapters"],
            "volumes": raw_data["data"]["volumes"],
            "status": raw_data["data"]["status"],
            "start_published": raw_data["data"]["published"]["from"],
            "end_published": raw_data["data"]["published"]["to"],
            "score": raw_data["data"]["score"],
            "rank": raw_data["data"]["rank"],
            "authors": [entry["name"] for entry in raw_data["data"]["authors"]],
            "genres": [entry["name"] for entry in raw_data["data"]["genres"]],
            "themes": [entry["name"] for entry in raw_data["data"]["themes"]]
        }

        full_data.append(manga_data)

    time.sleep(1)

 40%|████      | 4/10 [00:08<00:12,  2.01s/it]

Can't get data in id 5 because data not available

 50%|█████     | 5/10 [00:11<00:12,  2.43s/it]

Can't get data in id 6 because data not available

100%|██████████| 10/10 [00:24<00:00,  2.50s/it]

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
full_data = []

for num_id in tqdm(range(1, 201)):

    resp = requests.get(f"https://api.jikan.moe/v4/manga/{num_id}/full")

    if resp.status_code == 404:
        print(f"Can't get data in id {num_id} because data not available")
        pass

    else:
        raw_data = resp.json()

        manga_data = {
            "manga_id": raw_data["data"]["mal_id"],
            "url_manga": raw_data["data"]["url"],
            "title": raw_data["data"]["title"],
            "title_english": raw_data["data"]["title_english"],
            "title_japanese": raw_data["data"]["title_japanese"],
            "chapters": raw_data["data"]["chapters"],
            "volumes": raw_data["data"]["volumes"],
            "status": raw_data["data"]["status"],
            "start_published": raw_data["data"]["published"]["from"],
            "end_published": raw_data["data"]["published"]["to"],
            "score": raw_data["data"]["score"],
            "rank": raw_data["data"]["rank"],
            "authors": [entry["name"] for entry in raw_data["data"]["authors"]],
            "genres": [entry["name"] for entry in raw_data["data"]["genres"]],
            "themes": [entry["name"] for entry in raw_data["data"]["themes"]]
        }

        full_data.append(manga_data)

    time.sleep(1)
```

</details>

---

In [278]:
full_data

[{'manga_id': 1,
  'url_manga': 'https://myanimelist.net/manga/1/Monster',
  'title': 'Monster',
  'title_english': 'Monster',
  'title_japanese': 'MONSTER',
  'chapters': 162,
  'volumes': 18,
  'status': 'Finished',
  'start_published': '1994-12-05T00:00:00+00:00',
  'end_published': '2001-12-20T00:00:00+00:00',
  'score': 9.16,
  'rank': 5,
  'authors': ['Urasawa, Naoki'],
  'genres': ['Award Winning', 'Drama', 'Mystery'],
  'themes': ['Adult Cast', 'Psychological']},
 {'manga_id': 2,
  'url_manga': 'https://myanimelist.net/manga/2/Berserk',
  'title': 'Berserk',
  'title_english': 'Berserk',
  'title_japanese': 'ベルセルク',
  'chapters': None,
  'volumes': None,
  'status': 'Publishing',
  'start_published': '1989-08-25T00:00:00+00:00',
  'end_published': None,
  'score': 9.47,
  'rank': 1,
  'authors': ['Miura, Kentarou', 'Studio Gaga'],
  'genres': ['Action',
   'Adventure',
   'Award Winning',
   'Drama',
   'Fantasy',
   'Horror',
   'Supernatural'],
  'themes': ['Gore', 'Military', 'Mythology', 'Psychological']},
 {'manga_id': 3,
  'url_manga': 'https://myanimelist.net/manga/3/20th_Century_Boys',
  'title': '20th Century Boys',
  'title_english': '20th Century Boys',
  'title_japanese': '20世紀少年',
  'chapters': 249,
  'volumes': 22,
  'status': 'Finished',
  'start_published': '1999-09-27T00:00:00+00:00',
  'end_published': '2006-04-24T00:00:00+00:00',
  'score': 8.94,
  'rank': 17,
  'authors': ['Urasawa, Naoki'],
  'genres': ['Award Winning', 'Drama', 'Mystery', 'Sci-Fi'],
  'themes': ['Historical', 'Psychological']},
 {'manga_id': 4,
  'url_manga': 'https://myanimelist.net/manga/4/Yokohama_Kaidashi_Kikou',
  'title': 'Yokohama Kaidashi Kikou',
  'title_english': 'Yokohama Kaidashi Kikou',
  'title_japanese': 'ヨコハマ買い出し紀行',
  'chapters': 142,
  'volumes': 14,
  'status': 'Finished',
  'start_published': '1994-04-25T00:00:00+00:00',
  'end_published': '2006-02-25T00:00:00+00:00',
  'score': 8.65,
  'rank': 75,
  'authors': ['Ashinano, Hitoshi'],
  'genres': ['Award Winning', 'Sci-Fi', 'Slice of Life'],
  'themes': ['Iyashikei']},
 {'manga_id': 7,
  'url_manga': 'https://myanimelist.net/manga/7/Hajime_no_Ippo',
  'title': 'Hajime no Ippo',
  'title_english': 'Hajime no Ippo: Fighting Spirit!',
  'title_japanese': 'はじめの一歩',
  'chapters': None,
  'volumes': None,
  'status': 'Publishing',
  'start_published': '1989-09-27T00:00:00+00:00',
  'end_published': None,
  'score': 8.74,
  'rank': 50,
  'authors': ['Morikawa, George'],
  'genres': ['Award Winning', 'Sports'],
  'themes': ['Combat Sports']},
 {'manga_id': 8,
  'url_manga': 'https://myanimelist.net/manga/8/Full_Moon_wo_Sagashite',
  'title': 'Full Moon wo Sagashite',
  'title_english': 'Full Moon wo Sagashite',
  'title_japanese': '満月〈フルムーン〉をさがして',
  'chapters': 35,
  'volumes': 7,
  'status': 'Finished',
  'start_published': '2001-12-01T00:00:00+00:00',
  'end_published': '2004-04-30T00:00:00+00:00',
  'score': 8.02,
  'rank': 718,
  'authors': ['Tanemura, Arina'],
  'genres': ['Comedy', 'Drama', 'Fantasy', 'Romance', 'Supernatural'],
  'themes': ['Music', 'Showbiz']},
 {'manga_id': 9,
  'url_manga': 'https://myanimelist.net/manga/9/Tsubasa__RESERVoir_CHRoNiCLE',
  'title': 'Tsubasa: RESERVoir CHRoNiCLE',
  'title_english': 'Tsubasa: RESERVoir CHRoNiCLE',
  'title_japanese': 'ツバサ -RESERVoir CHRoNiCLE-',
  'chapters': 233,
  'volumes': 28,
  'status': 'Finished',
  'start_published': '2003-05-21T00:00:00+00:00',
  'end_published': '2009-10-07T00:00:00+00:00',
  'score': 8.29,
  'rank': 313,
  'authors': ['CLAMP'],
  'genres': ['Action', 'Adventure', 'Drama', 'Fantasy'],
  'themes': []},
 {'manga_id': 10,
  'url_manga': 'https://myanimelist.net/manga/10/xxxHOLiC',
  'title': 'xxxHOLiC',
  'title_english': 'xxxHOLiC',
  'title_japanese': 'xxxHOLiC',
  'chapters': 213,
  'volumes': 19,
  'status': 'Finished',
  'start_published': '2003-02-24T00:00:00+00:00',
  'end_published': '2011-02-09T00:00:00+00:00',
  'score': 8.37,
  'rank': 237,
  'authors': ['CLAMP'],
  'genres': ['Comedy', 'Drama', 'Mystery', 'Supernatural'],
  'themes': []}]

### **7d**
---

- Setelah berhasil mengambil seluruh data yang diinginkan, kita akan convert menjadi DataFrame

In [279]:
manga_data = pd.DataFrame(full_data)

manga_data.head()

,manga_id,url_manga,title,title_english,title_japanese,chapters,volumes,status,start_published,end_published,score,rank,authors,genres,themes
0,1,https://myanimelist.net/manga/1/Monster,Monster,Monster,MONSTER,162.0,18.0,Finished,1994-12-05T00:00:00+00:00,2001-12-20T00:00:00+00:00,9.16,5,"[Urasawa, Naoki]","[Award Winning, Drama, Mystery]","[Adult Cast, Psychological]"
1,2,https://myanimelist.net/manga/2/Berserk,Berserk,Berserk,ベルセルク,NaN,NaN,Publishing,1989-08-25T00:00:00+00:00,None,9.47,1,"[Miura, Kentarou, Studio Gaga]","[Action, Adventure, Award Winning, Drama, Fant...","[Gore, Military, Mythology, Psychological]"
2,3,https://myanimelist.net/manga/3/20th_Century_Boys,20th Century Boys,20th Century Boys,20世紀少年,249.0,22.0,Finished,1999-09-27T00:00:00+00:00,2006-04-24T00:00:00+00:00,8.94,17,"[Urasawa, Naoki]","[Award Winning, Drama, Mystery, Sci-Fi]","[Historical, Psychological]"
3,4,https://myanimelist.net/manga/4/Yokohama_Kaida...,Yokohama Kaidashi Kikou,Yokohama Kaidashi Kikou,ヨコハマ買い出し紀行,142.0,14.0,Finished,1994-04-25T00:00:00+00:00,2006-02-25T00:00:00+00:00,8.65,75,"[Ashinano, Hitoshi]","[Award Winning, Sci-Fi, Slice of Life]",[Iyashikei]
4,7,https://myanimelist.net/manga/7/Hajime_no_Ippo,Hajime no Ippo,Hajime no Ippo: Fighting Spirit!,はじめの一歩,NaN,NaN,Publishing,1989-09-27T00:00:00+00:00,None,8.74,50,"[Morikawa, George]","[Award Winning, Sports]",[Combat Sports]

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
manga_data = pd.DataFrame(full_data)

manga_data.head()
```

</details>

---

Simpan hasil outputnya dalam bentuk `csv` dengan filename `full_manga_data.csv`

In [107]:
manga_data.to_csv("full_manga_data.csv", index = False)

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
manga_data.to_csv("full_manga_data.csv", index = False)
```

</details>

---

## **8**
---

- Pada proses ini, kita akan melakukan proses trial and error untuk Transform data sebelum membuat ETL Pipeline
- Langkah - langkah yang akan kita lakukan:
    1. Impute missing values:
        - `chapters` dan `volumes` dengan value `Not Found`
        - `score` dan `rank` dengan value `0`
    2. Convert `start_published` dan `end_published` ke tipe data datetime
    3. Convert `rank` menjadi `int`

### **8a**
---

Ada beberapa kolom yang perlu kita treat:
- Lakukan proses impute value untuk kolom  `chapters` dan `volumes` dengan value `Not Found`
- Lakukan proses impute value untuk kolom `score` dan `rank` dengan value `0`

In [280]:
# check missing values
manga_data.isnull().sum()

manga_id           0
url_manga          0
title              0
title_english      0
title_japanese     0
chapters           2
volumes            2
status             0
start_published    0
end_published      2
score              0
rank               0
authors            0
genres             0
themes             0
dtype: int64

In [281]:
manga_data["chapters"] = manga_data["chapters"].fillna(value = "Not Found")
manga_data["volumes"] = manga_data["volumes"].fillna(value = "Not Found")

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
manga_data["chapters"] = manga_data["chapters"].fillna(value = "Not Found")
manga_data["volumes"] = manga_data["volumes"].fillna(value = "Not Found")
```

</details>

---

In [282]:
# check the value if already change
manga_data[manga_data["chapters"] == "Not Found"]

,manga_id,url_manga,title,title_english,title_japanese,chapters,volumes,status,start_published,end_published,score,rank,authors,genres,themes
1,2,https://myanimelist.net/manga/2/Berserk,Berserk,Berserk,ベルセルク,Not Found,Not Found,Publishing,1989-08-25T00:00:00+00:00,None,9.47,1,"[Miura, Kentarou, Studio Gaga]","[Action, Adventure, Award Winning, Drama, Fant...","[Gore, Military, Mythology, Psychological]"
4,7,https://myanimelist.net/manga/7/Hajime_no_Ippo,Hajime no Ippo,Hajime no Ippo: Fighting Spirit!,はじめの一歩,Not Found,Not Found,Publishing,1989-09-27T00:00:00+00:00,None,8.74,50,"[Morikawa, George]","[Award Winning, Sports]",[Combat Sports]

In [283]:
manga_data["score"] = manga_data["score"].fillna(value = 0)
manga_data["rank"] = manga_data["rank"].fillna(value = 0)

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
manga_data["score"] = manga_data["score"].fillna(value = 0)
manga_data["rank"] = manga_data["rank"].fillna(value = 0)
```

</details>

---

In [112]:
# check the values 0 already exists in score column
manga_data[manga_data["score"] == 0]

Empty DataFrame
Columns: [manga_id, url_manga, title, title_english, title_japanese, chapters, volumes, status, start_published, end_published, score, rank, authors, genres, themes]
Index: []

In [284]:
# check the missing values
manga_data.isnull().sum()

manga_id           0
url_manga          0
title              0
title_english      0
title_japanese     0
chapters           0
volumes            0
status             0
start_published    0
end_published      2
score              0
rank               0
authors            0
genres             0
themes             0
dtype: int64

### **8b**
---

- Sekarang, lakukan convert `start_published` dan `end_published` ke tipe data datetime

In [285]:
manga_data["start_published"] = pd.to_datetime(manga_data["start_published"])

manga_data["start_published"]

0   1994-12-05 00:00:00+00:00
1   1989-08-25 00:00:00+00:00
2   1999-09-27 00:00:00+00:00
3   1994-04-25 00:00:00+00:00
4   1989-09-27 00:00:00+00:00
5   2001-12-01 00:00:00+00:00
6   2003-05-21 00:00:00+00:00
7   2003-02-24 00:00:00+00:00
Name: start_published, dtype: datetime64[ns, UTC]

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
manga_data["start_published"] = pd.to_datetime(manga_data["start_published"])

manga_data["start_published"]
```

</details>

---

In [286]:
manga_data["end_published"] = pd.to_datetime(manga_data["end_published"])

manga_data["end_published"]

0   2001-12-20 00:00:00+00:00
1                         NaT
2   2006-04-24 00:00:00+00:00
3   2006-02-25 00:00:00+00:00
4                         NaT
5   2004-04-30 00:00:00+00:00
6   2009-10-07 00:00:00+00:00
7   2011-02-09 00:00:00+00:00
Name: end_published, dtype: datetime64[ns, UTC]

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
manga_data["end_published"] = pd.to_datetime(manga_data["end_published"])

manga_data["end_published"]
```

</details>

---

In [287]:
# check info datatype
manga_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   manga_id         8 non-null      int64
 1   url_manga        8 non-null      object
 2   title            8 non-null      object
 3   title_english    8 non-null      object
 4   title_japanese   8 non-null      object
 5   chapters         8 non-null      object
 6   volumes          8 non-null      object
 7   status           8 non-null      object
 8   start_published  8 non-null      datetime64[ns, UTC]
 9   end_published    6 non-null      datetime64[ns, UTC]
 10  score            8 non-null      float64
 11  rank             8 non-null      int64
 12  authors          8 non-null      object
 13  genres           8 non-null      object
 14  themes           8 non-null      object
dtypes: datetime64[ns, UTC](2), float64(1), int64(2), object(10)
memory usage: 1.1+ KB

### **8c**
---

- Terakhir, kita ubah tipe data dari kolom `rank` menjadi `int`

In [288]:
manga_data["rank"] = manga_data["rank"].astype(int)

manga_data["rank"]

0      5
1      1
2     17
3     75
4     50
5    718
6    313
7    237
Name: rank, dtype: int64

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
manga_data["rank"] = manga_data["rank"].astype(int)

manga_data["rank"]
```

</details>

---

## **9**
---

- Buatlah Luigi Pipeline dengan menggabungkan Task yang sudah kita lakukan sebelumnya
- Sama seperti di task sebelumnya, kita akan simpan file `csv` pada tiap proses nya

In [289]:
class ExtractAPIMangaData(luigi.Task):

    def requires(self):
        pass

    def run(self):
        full_data = []

        for num_id in tqdm(range(1, 11)):

            resp = requests.get(f"https://api.jikan.moe/v4/manga/{num_id}/full")

            if resp.status_code == 404:
                pass

            else:
                raw_data = resp.json()

                manga_data = {
                    "manga_id": raw_data["data"]["mal_id"],
                    "url_manga": raw_data["data"]["url"],
                    "title": raw_data["data"]["title"],
                    "title_english": raw_data["data"]["title_english"],
                    "title_japanese": raw_data["data"]["title_japanese"],
                    "chapters": raw_data["data"]["chapters"],
                    "volumes": raw_data["data"]["volumes"],
                    "status": raw_data["data"]["status"],
                    "start_published": raw_data["data"]["published"]["from"],
                    "end_published": raw_data["data"]["published"]["to"],
                    "score": raw_data["data"]["score"],
                    "rank": raw_data["data"]["rank"],
                    "authors": [entry["name"] for entry in raw_data["data"]["authors"]],
                    "genres": [entry["name"] for entry in raw_data["data"]["genres"]],
                    "themes": [entry["name"] for entry in raw_data["data"]["themes"]]
                }

                full_data.append(manga_data)

            time.sleep(1)

        manga_data = pd.DataFrame(full_data)

        manga_data.to_csv(self.output().path, index = False)

    def output(self):
        return luigi.LocalTarget("data/raw/extract_manga_data.csv")

class TransformMangaData(luigi.Task):

    def requires(self):
        return ExtractAPIMangaData()

    def run(self):
        transform_manga_data = pd.read_csv(self.input().path)

        transform_manga_data["chapters"] = transform_manga_data["chapters"].fillna(value = "Not Found")
        transform_manga_data["volumes"] = transform_manga_data["volumes"].fillna(value = "Not Found")

        transform_manga_data["score"] = transform_manga_data["score"].fillna(value = 0)
        transform_manga_data["rank"] = transform_manga_data["rank"].fillna(value = 0)

        transform_manga_data["start_published"] = pd.to_datetime(transform_manga_data["start_published"])
        transform_manga_data["end_published"] = pd.to_datetime(transform_manga_data["end_published"])

        transform_manga_data["rank"] = transform_manga_data["rank"].astype(int)

        transform_manga_data.to_csv(self.output().path, index = False)

    def output(self):
        return luigi.LocalTarget("data/transform/transform_manga_data.csv")

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
class ExtractAPIMangaData(luigi.Task):

    def requires(self):
        pass

    def run(self):
        full_data = []

        for num_id in tqdm(range(1, 201)):

            resp = requests.get(f"https://api.jikan.moe/v4/manga/{num_id}/full")

            if resp.status_code == 404:
                pass

            else:
                raw_data = resp.json()

                manga_data = {
                    "manga_id": raw_data["data"]["mal_id"],
                    "url_manga": raw_data["data"]["url"],
                    "title": raw_data["data"]["title"],
                    "title_english": raw_data["data"]["title_english"],
                    "title_japanese": raw_data["data"]["title_japanese"],
                    "chapters": raw_data["data"]["chapters"],
                    "volumes": raw_data["data"]["volumes"],
                    "status": raw_data["data"]["status"],
                    "start_published": raw_data["data"]["published"]["from"],
                    "end_published": raw_data["data"]["published"]["to"],
                    "score": raw_data["data"]["score"],
                    "rank": raw_data["data"]["rank"],
                    "authors": [entry["name"] for entry in raw_data["data"]["authors"]],
                    "genres": [entry["name"] for entry in raw_data["data"]["genres"]],
                    "themes": [entry["name"] for entry in raw_data["data"]["themes"]]
                }

                full_data.append(manga_data)

            time.sleep(1)

        manga_data = pd.DataFrame(full_data)

        manga_data.to_csv(self.output().path, index = False)

    def output(self):
        return luigi.LocalTarget("live_class_w7/data/raw/extract_manga_data.csv")

class TransformMangaData(luigi.Task):

    def requires(self):
        return ExtractAPIMangaData()

    def run(self):
        transform_manga_data = pd.read_csv(self.input().path)

        transform_manga_data["chapters"] = transform_manga_data["chapters"].fillna(value = "Not Found")
        transform_manga_data["volumes"] = transform_manga_data["volumes"].fillna(value = "Not Found")

        transform_manga_data["score"] = transform_manga_data["score"].fillna(value = 0)
        transform_manga_data["rank"] = transform_manga_data["rank"].fillna(value = 0)

        transform_manga_data["start_published"] = pd.to_datetime(transform_manga_data["start_published"])
        transform_manga_data["end_published"] = pd.to_datetime(transform_manga_data["end_published"])

        transform_manga_data["rank"] = transform_manga_data["rank"].astype(int)

        transform_manga_data.to_csv(self.output().path, index = False)

    def output(self):
        return luigi.LocalTarget("live_class_w7/data/transform/transform_manga_data.csv")
```

</details>

---

In [290]:
luigi.build([ExtractAPIMangaData(), TransformMangaData()], local_scheduler = True)

DEBUG: Checking if ExtractAPIMangaData() is complete
INFO: Informed scheduler that task   ExtractAPIMangaData__99914b932b   has status   PENDING
DEBUG: Checking if TransformMangaData() is complete
DEBUG: Checking if ExtractAPIMangaData() is complete
INFO: Informed scheduler that task   TransformMangaData__99914b932b   has status   PENDING
INFO: Informed scheduler that task   ExtractAPIMangaData__99914b932b   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 2
INFO: [pid 14066] Worker Worker(salt=9368067192, workers=1, host=DESKTOP-KIQCHDD, username=rosy, pid=14066) running   ExtractAPIMangaData()
100%|██████████| 10/10 [00:22<00:00,  2.24s/it]
INFO: [pid 14066] Worker Worker(salt=9368067192, workers=1, host=DESKTOP-KIQCHDD, username=rosy, pid=14066) done      ExtractAPIMangaData()
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   ExtractAPIMangaData__99914b932b   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 14066] Worker Worker(salt=9368067192, workers=1, host=DESKTOP-KIQCHDD, username=rosy, pid=14066) running   TransformMangaData()
INFO: [pid 14066] Worker Worker(salt=9368067192, workers=1, host=DESKTOP-KIQCHDD, username=rosy, pid=14066) done      TransformMangaData()
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   TransformMangaData__99914b932b   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO: Worker Worker(salt=9368067192, workers=1, host=DESKTOP-KIQCHDD, username=rosy, pid=14066) was stopped. Shutting down Keep-Alive thread
INFO:
===== Luigi Execution Summary =====

Scheduled 2 tasks of which:
* 2 ran successfully:
    - 1 ExtractAPIMangaData()
    - 1 TransformMangaData()

This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====

True

## **10**
---

- Kita sudah masuk ke tahap akhir, yaitu proses Load
- Kita akan memasukkan data Anime dan Manga ke dalam satu database yang sama
- Database hosting yang akan kita pakai adalah https://neon.tech/
- Buatlah akun free dari Neon dan buatlah database dengan nama `recommender_system_db`
- Database yang digunakan adalah PostgreSQL

### **10a**
---

- Jika sudah membuat akun dan database di Neon, langkah selanjutnya adalah membuat function untuk melakukan koneksi ke database dengan menggunakan Pandas
- Untuk nama user, database, password, dan host mengikuti akun yang dimiliki

In [121]:
from sqlalchemy import create_engine

In [ ]:
postgresql://neondb_owner:kOapXW9wgn4G@ep-solitary-breeze-a5b17r3a.us-east-2.aws.neon.tech/neondb?sslmode=require

In [291]:
DB_USERNAME = "neondb_owner"
DB_PASSWORD = "kOapXW9wgn4G"
DB_HOST = "ep-solitary-breeze-a5b17r3a.us-east-2.aws.neon.tech"
DB_NAME = "neondb"
DB_PORT='5432'

In [292]:
def postgres_engine():
    engine = create_engine(f"postgresql://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}")

    return engine

In [293]:
postgres_engine()

Engine(postgresql://neondb_owner:***@ep-solitary-breeze-a5b17r3a.us-east-2.aws.neon.tech:5432/neondb)

### **10b**
---

Schema table dari masing - masing data

```sql
CREATE TABLE public.anime_data (
	title varchar NULL,
	link_mal varchar NULL,
	release_date timestamp NULL,
	anime_episode int NULL,
	anime_duration int NULL,
	anime_genre varchar NULL,
	img_link varchar NULL,
	description varchar NULL,
	studio varchar NULL,
	"source" varchar NULL,
	show_type varchar NULL,
	created_at timestamp NOT NULL DEFAULT now()
);

```


```sql
CREATE TABLE public.manga_data (
	manga_id int NULL,
	url_manga varchar NULL,
	title varchar NULL,
	title_english varchar NULL,
	title_japanese varchar NULL,
	chapters varchar NULL,
	volumes varchar NULL,
	status varchar NULL,
	start_published timestamp NULL,
	end_published timestamp NULL,
	score float4 NULL,
	"rank" int NULL,
	authors varchar NULL,
	genres varchar NULL,
	themes varchar NULL,
	created_at timestamp NOT NULL DEFAULT now()
);

```

- Buatlah Luigi Task load untuk menyimpan Anime dan Manga data menjadi satu database yang sama
- Kita juga perlu menyimpan outputnya dalam bentuk `csv`, untuk Anime data kita beri nama `load_anime_data_winter.csv` dan untuk Manga data kita beri nama `load_manga_data.csv`

In [294]:
class LoadRecommenderSystemData(luigi.Task):
    def requires(self):
        return [TransformAnimeData(),
                TransformMangaData()]

    def output(self):
        return [luigi.LocalTarget("data/load/load_anime_data_winter.csv"),
                luigi.LocalTarget("data/load/load_manga_data.csv")]

    def run(self):
        # init postgres engine
        engine = postgres_engine()

        # read data from previous task
        anime_data = pd.read_csv(self.input()[0].path)
        manga_data = pd.read_csv(self.input()[1].path)

        # init table name
        anime_data_table = "anime_data"
        manga_data_table = "manga_data"

        # insert to database
        anime_data.to_sql(name = anime_data_table,
                          con = engine,
                          if_exists = "replace",
                          index = False)

        manga_data.to_sql(name = manga_data_table,
                          con = engine,
                          if_exists = "replace",
                          index = False)

        # save the process
        anime_data.to_csv(self.output()[0].path, index = False)
        manga_data.to_csv(self.output()[1].path, index = False)

<details>
    <summary><b>Klik untuk melihat kunci jawaban</b></summary>

```python
class LoadRecommenderSystemData(luigi.Task):
    def requires(self):
        return [TransformAnimeData(),
                TransformMangaData()]

    def output(self):
        return [luigi.LocalTarget("live_class_w7/data/load/load_anime_data_winter.csv"),
                luigi.LocalTarget("live_class_w7/data/load/load_manga_data.csv")]

    def run(self):
        # init postgres engine
        engine = postgres_engine()

        # read data from previous task
        anime_data = pd.read_csv(self.input()[0].path)
        manga_data = pd.read_csv(self.input()[1].path)

        # init table name
        anime_data_table = "anime_data"
        manga_data_table = "manga_data"

        # insert to database
        anime_data.to_sql(name = anime_data_table,
                          con = engine,
                          if_exists = "append",
                          index = False)

        manga_data.to_sql(name = manga_data_table,
                          con = engine,
                          if_exists = "append",
                          index = False)

        # save the process
        anime_data.to_csv(self.output()[0].path, index = False)
        manga_data.to_csv(self.output()[1].path, index = False)
```

</details>

---

In [296]:
# run all the process
luigi.build([ExtractAnimeData(),
             ExtractAPIMangaData(),
             TransformAnimeData(),
             TransformMangaData(),
             LoadRecommenderSystemData()],
             local_scheduler = False)

DEBUG: Checking if ExtractAnimeData(year=2024, season=winter) is complete
INFO: Informed scheduler that task   ExtractAnimeData_winter_2024_307ccc7558   has status   DONE
DEBUG: Checking if ExtractAPIMangaData() is complete
INFO: Informed scheduler that task   ExtractAPIMangaData__99914b932b   has status   DONE
DEBUG: Checking if TransformAnimeData() is complete
INFO: Informed scheduler that task   TransformAnimeData__99914b932b   has status   DONE
DEBUG: Checking if TransformMangaData() is complete
INFO: Informed scheduler that task   TransformMangaData__99914b932b   has status   DONE
DEBUG: Checking if LoadRecommenderSystemData() is complete
INFO: Informed scheduler that task   LoadRecommenderSystemData__99914b932b   has status   DONE
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO:
===== Luigi Execution Summary =====

Scheduled 5 tasks of which:
* 5 complete ones were encountered:
    - 1 ExtractAPIMangaData()
    - 1 ExtractAnimeData(year=2024, season=winter)
    - 1 LoadRecommenderSystemData()
    - 1 TransformAnimeData()
    - 1 TransformMangaData()

Did not run any tasks
This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====

True

Untuk code yang dalam bentuk Python script bisa cek pada repository berikut https://github.com/shandytepe/live-class-luigi-pacmann